/**
 * Seed data for Magic English word bank.
 * 500 words covering multiple themes × grades 1-6.
 * Sentence-driven: each word comes with a child-friendly example sentence.
 */
export const seedWords = [
  { word: 'cat', translation: '猫', phonetic: '/kæt/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'I have a cute cat at home.', sentenceCn: '我家里有一只可爱的猫。' },
  { word: 'dog', translation: '狗', phonetic: '/dɒɡ/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The dog likes to run in the park.', sentenceCn: '狗喜欢在公园里跑。' },
  { word: 'fish', translation: '鱼', phonetic: '/fɪʃ/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'There are many fish in the river.', sentenceCn: '河里有很多鱼。' },
  { word: 'bird', translation: '鸟', phonetic: '/bɜːrd/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'A little bird is singing in the tree.', sentenceCn: '一只小鸟在树上唱歌。' },
  { word: 'pig', translation: '猪', phonetic: '/pɪɡ/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The pig is sleeping on the farm.', sentenceCn: '猪在农场里睡觉。' },
  { word: 'cow', translation: '奶牛', phonetic: '/kaʊ/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The cow gives us milk every day.', sentenceCn: '奶牛每天给我们产奶。' },
  { word: 'duck', translation: '鸭子', phonetic: '/dʌk/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The duck can swim very fast.', sentenceCn: '鸭子能游得很快。' },
  { word: 'hen', translation: '母鸡', phonetic: '/hen/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The hen lays eggs in the morning.', sentenceCn: '母鸡早上生蛋。' },
  { word: 'frog', translation: '青蛙', phonetic: '/frɒɡ/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The frog jumps into the water.', sentenceCn: '青蛙跳进水里。' },
  { word: 'bear', translation: '熊', phonetic: '/ber/', difficulty: 1, gradeLevel: 1, theme: 'animal' , sentence: 'The big bear lives in the forest.', sentenceCn: '大熊住在森林里。' },
  { word: 'lion', translation: '狮子', phonetic: '/ˈlaɪən/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'The lion is the king of animals.', sentenceCn: '狮子是百兽之王。' },
  { word: 'tiger', translation: '老虎', phonetic: '/ˈtaɪɡər/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'A tiger has orange and black stripes.', sentenceCn: '老虎有橙色和黑色的条纹。' },
  { word: 'monkey', translation: '猴子', phonetic: '/ˈmʌŋki/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'The monkey likes to eat bananas.', sentenceCn: '猴子喜欢吃香蕉。' },
  { word: 'rabbit', translation: '兔子', phonetic: '/ˈræbɪt/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'The rabbit has long ears and a short tail.', sentenceCn: '兔子有长耳朵和短尾巴。' },
  { word: 'elephant', translation: '大象', phonetic: '/ˈelɪfənt/', difficulty: 3, gradeLevel: 2, theme: 'animal' , sentence: 'An elephant is very big and strong.', sentenceCn: '大象非常大而且强壮。' },
  { word: 'mouse', translation: '老鼠', phonetic: '/maʊs/', difficulty: 1, gradeLevel: 2, theme: 'animal' , sentence: 'The little mouse is hiding in the hole.', sentenceCn: '小老鼠躲在洞里。' },
  { word: 'snake', translation: '蛇', phonetic: '/sneɪk/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'A snake has no legs but can move fast.', sentenceCn: '蛇没有腿但能快速移动。' },
  { word: 'horse', translation: '马', phonetic: '/hɔːrs/', difficulty: 1, gradeLevel: 2, theme: 'animal' , sentence: 'I want to ride a horse one day.', sentenceCn: '我想有一天骑一次马。' },
  { word: 'sheep', translation: '绵羊', phonetic: '/ʃiːp/', difficulty: 1, gradeLevel: 2, theme: 'animal' , sentence: 'The sheep has white wool on its body.', sentenceCn: '绵羊身上有白色的羊毛。' },
  { word: 'chicken', translation: '鸡', phonetic: '/ˈtʃɪkɪn/', difficulty: 2, gradeLevel: 2, theme: 'animal' , sentence: 'My grandma keeps chickens in her yard.', sentenceCn: '我奶奶在院子里养鸡。' },
  { word: 'dolphin', translation: '海豚', phonetic: '/ˈdɑːlfɪn/', difficulty: 3, gradeLevel: 3, theme: 'animal' , sentence: 'Dolphins are very smart and friendly.', sentenceCn: '海豚非常聪明而且友好。' },
  { word: 'giraffe', translation: '长颈鹿', phonetic: '/dʒəˈræf/', difficulty: 3, gradeLevel: 3, theme: 'animal' , sentence: 'A giraffe has a very long neck.', sentenceCn: '长颈鹿有非常长的脖子。' },
  { word: 'panda', translation: '熊猫', phonetic: '/ˈpændə/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'Pandas love to eat bamboo.', sentenceCn: '熊猫喜欢吃竹子。' },
  { word: 'parrot', translation: '鹦鹉', phonetic: '/ˈpærət/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'The parrot can learn to speak.', sentenceCn: '鹦鹉能学说话。' },
  { word: 'whale', translation: '鲸鱼', phonetic: '/weɪl/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'A whale is the biggest animal in the sea.', sentenceCn: '鲸鱼是海里最大的动物。' },
  { word: 'shark', translation: '鲨鱼', phonetic: '/ʃɑːrk/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'Sharks have very sharp teeth.', sentenceCn: '鲨鱼有非常锋利的牙齿。' },
  { word: 'kangaroo', translation: '袋鼠', phonetic: '/ˌkæŋɡəˈruː/', difficulty: 4, gradeLevel: 3, theme: 'animal' , sentence: 'A kangaroo carries its baby in a pouch.', sentenceCn: '袋鼠用育儿袋装着小袋鼠。' },
  { word: 'butterfly', translation: '蝴蝶', phonetic: '/ˈbʌtərflaɪ/', difficulty: 3, gradeLevel: 3, theme: 'animal' , sentence: 'The butterfly has beautiful colorful wings.', sentenceCn: '蝴蝶有美丽的彩色翅膀。' },
  { word: 'eagle', translation: '鹰', phonetic: '/ˈiːɡəl/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'The eagle can fly very high in the sky.', sentenceCn: '鹰能在天空中飞得很高。' },
  { word: 'turtle', translation: '海龟', phonetic: '/ˈtɜːrtl/', difficulty: 2, gradeLevel: 3, theme: 'animal' , sentence: 'The turtle walks very slowly on the beach.', sentenceCn: '海龟在海滩上走得很慢。' },
  { word: 'penguin', translation: '企鹅', phonetic: '/ˈpeŋɡwɪn/', difficulty: 3, gradeLevel: 4, theme: 'animal' , sentence: 'Penguins live in very cold places.', sentenceCn: '企鹅住在非常冷的地方。' },
  { word: 'tortoise', translation: '乌龟', phonetic: '/ˈtɔːrtəs/', difficulty: 3, gradeLevel: 4, theme: 'animal' , sentence: 'The tortoise carries its house on its back.', sentenceCn: '乌龟把它的房子背在背上。' },
  { word: 'squirrel', translation: '松鼠', phonetic: '/ˈskwɜːrəl/', difficulty: 4, gradeLevel: 4, theme: 'animal' , sentence: 'The squirrel collects nuts for winter.', sentenceCn: '松鼠为冬天收集坚果。' },
  { word: 'crocodile', translation: '鳄鱼', phonetic: '/ˈkrɑːkədaɪl/', difficulty: 4, gradeLevel: 4, theme: 'animal' , sentence: 'A crocodile has a big mouth with sharp teeth.', sentenceCn: '鳄鱼有一张长满尖牙的大嘴。' },
  { word: 'octopus', translation: '章鱼', phonetic: '/ˈɑːktəpʊs/', difficulty: 3, gradeLevel: 4, theme: 'animal' , sentence: 'An octopus has eight long arms.', sentenceCn: '章鱼有八条长手臂。' },
  { word: 'camel', translation: '骆驼', phonetic: '/ˈkæməl/', difficulty: 3, gradeLevel: 4, theme: 'animal' , sentence: 'Camels can walk for days without water.', sentenceCn: '骆驼能走好几天不喝水。' },
  { word: 'dragonfly', translation: '蜻蜓', phonetic: '/ˈdræɡənflaɪ/', difficulty: 4, gradeLevel: 4, theme: 'animal' , sentence: 'The dragonfly flies over the pond.', sentenceCn: '蜻蜓在池塘上方飞。' },
  { word: 'ant', translation: '蚂蚁', phonetic: '/ænt/', difficulty: 2, gradeLevel: 4, theme: 'animal' , sentence: 'Ants work together to carry food.', sentenceCn: '蚂蚁一起合作搬运食物。' },
  { word: 'bee', translation: '蜜蜂', phonetic: '/biː/', difficulty: 1, gradeLevel: 4, theme: 'animal' , sentence: 'Bees make sweet honey from flowers.', sentenceCn: '蜜蜂从花中酿出甜甜的蜂蜜。' },
  { word: 'spider', translation: '蜘蛛', phonetic: '/ˈspaɪdər/', difficulty: 3, gradeLevel: 4, theme: 'animal' , sentence: 'The spider makes a web to catch food.', sentenceCn: '蜘蛛织网来捕食。' },
  { word: 'wolf', translation: '狼', phonetic: '/wʊlf/', difficulty: 3, gradeLevel: 5, theme: 'animal' , sentence: 'A wolf howls at the moon at night.', sentenceCn: '狼在夜晚对着月亮嚎叫。' },
  { word: 'fox', translation: '狐狸', phonetic: '/fɑːks/', difficulty: 2, gradeLevel: 5, theme: 'animal' , sentence: 'The fox has a big bushy tail.', sentenceCn: '狐狸有一条毛茸茸的大尾巴。' },
  { word: 'deer', translation: '鹿', phonetic: '/dɪr/', difficulty: 2, gradeLevel: 5, theme: 'animal' , sentence: 'The deer runs quickly through the woods.', sentenceCn: '鹿在树林里跑得很快。' },
  { word: 'owl', translation: '猫头鹰', phonetic: '/aʊl/', difficulty: 2, gradeLevel: 5, theme: 'animal' , sentence: 'An owl can see very well at night.', sentenceCn: '猫头鹰在夜里看得非常清楚。' },
  { word: 'bat', translation: '蝙蝠', phonetic: '/bæt/', difficulty: 2, gradeLevel: 5, theme: 'animal' , sentence: 'A bat sleeps upside down in the cave.', sentenceCn: '蝙蝠在洞穴里倒挂着睡觉。' },
  { word: 'swan', translation: '天鹅', phonetic: '/swɑːn/', difficulty: 3, gradeLevel: 5, theme: 'animal' , sentence: 'The white swan glides across the lake.', sentenceCn: '白色的天鹅在湖面上滑行。' },
  { word: 'peacock', translation: '孔雀', phonetic: '/ˈpiːkɑːk/', difficulty: 4, gradeLevel: 5, theme: 'animal' , sentence: 'The peacock shows its beautiful tail feathers.', sentenceCn: '孔雀展示它美丽的尾羽。' },
  { word: 'leopard', translation: '豹', phonetic: '/ˈlepərd/', difficulty: 4, gradeLevel: 5, theme: 'animal' , sentence: 'A leopard can run faster than most animals.', sentenceCn: '豹比大多数动物跑得都快。' },
  { word: 'seal', translation: '海豹', phonetic: '/siːl/', difficulty: 3, gradeLevel: 5, theme: 'animal' , sentence: 'The seal likes to swim in the cold ocean.', sentenceCn: '海豹喜欢在冰冷的海里游泳。' },
  { word: 'gorilla', translation: '大猩猩', phonetic: '/ɡəˈrɪlə/', difficulty: 4, gradeLevel: 6, theme: 'animal' , sentence: 'A gorilla is very strong and lives in groups.', sentenceCn: '大猩猩非常强壮，过着群居生活。' },
  { word: 'chimpanzee', translation: '黑猩猩', phonetic: '/ˌtʃɪmpænˈziː/', difficulty: 5, gradeLevel: 6, theme: 'animal' , sentence: 'Chimpanzees are our closest animal relatives.', sentenceCn: '黑猩猩是与我们最亲近的动物亲戚。' },
  { word: 'rhinoceros', translation: '犀牛', phonetic: '/raɪˈnɑːsərəs/', difficulty: 5, gradeLevel: 6, theme: 'animal' , sentence: 'The rhinoceros has a large horn on its nose.', sentenceCn: '犀牛鼻子上有一个大角。' },
  { word: 'hippopotamus', translation: '河马', phonetic: '/ˌhɪpəˈpɑːtəməs/', difficulty: 5, gradeLevel: 6, theme: 'animal' , sentence: 'A hippopotamus spends most of its time in water.', sentenceCn: '河马大部分时间都待在水里。' },
  { word: 'flamingo', translation: '火烈鸟', phonetic: '/fləˈmɪŋɡoʊ/', difficulty: 4, gradeLevel: 6, theme: 'animal' , sentence: 'Flamingos stand on one leg in the shallow water.', sentenceCn: '火烈鸟在浅水中单腿站立。' },
  { word: 'chameleon', translation: '变色龙', phonetic: '/kəˈmiːliən/', difficulty: 5, gradeLevel: 6, theme: 'animal' , sentence: 'A chameleon can change its skin color.', sentenceCn: '变色龙能改变皮肤的颜色。' },
  { word: 'jellyfish', translation: '水母', phonetic: '/ˈdʒelifɪʃ/', difficulty: 4, gradeLevel: 6, theme: 'animal' , sentence: 'Do not touch a jellyfish, it can sting you.', sentenceCn: '不要碰水母，它会蜇你。' },
  { word: 'scorpion', translation: '蝎子', phonetic: '/ˈskɔːrpiən/', difficulty: 4, gradeLevel: 6, theme: 'animal' , sentence: 'A scorpion has a sharp stinger on its tail.', sentenceCn: '蝎子尾巴上有一根锋利的毒刺。' },
  { word: 'dinosaur', translation: '恐龙', phonetic: '/ˈdaɪnəsɔːr/', difficulty: 3, gradeLevel: 6, theme: 'animal' , sentence: 'Dinosaurs lived on Earth long ago.', sentenceCn: '恐龙很久以前生活在地球上。' },
  { word: 'dragon', translation: '龙', phonetic: '/ˈdræɡən/', difficulty: 3, gradeLevel: 6, theme: 'animal' , sentence: 'In stories, a dragon can breathe fire.', sentenceCn: '在故事里，龙能喷火。' },
  { word: 'unicorn', translation: '独角兽', phonetic: '/ˈjuːnɪkɔːrn/', difficulty: 4, gradeLevel: 6, theme: 'animal' , sentence: 'A unicorn is a magical horse with one horn.', sentenceCn: '独角兽是一只有一只角的神奇马。' },
  { word: 'apple', translation: '苹果', phonetic: '/ˈæpəl/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'I eat an apple every day to stay healthy.', sentenceCn: '我每天吃一个苹果保持健康。' },
  { word: 'banana', translation: '香蕉', phonetic: '/bəˈnænə/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'Monkeys love to eat yellow bananas.', sentenceCn: '猴子喜欢吃黄色的香蕉。' },
  { word: 'milk', translation: '牛奶', phonetic: '/mɪlk/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'Drinking milk helps you grow taller.', sentenceCn: '喝牛奶能帮助你长高。' },
  { word: 'egg', translation: '鸡蛋', phonetic: '/eɡ/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'I have an egg and milk for breakfast.', sentenceCn: '我早餐吃一个鸡蛋和牛奶。' },
  { word: 'rice', translation: '米饭', phonetic: '/raɪs/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'We eat rice with vegetables for lunch.', sentenceCn: '我们午饭吃米饭配蔬菜。' },
  { word: 'bread', translation: '面包', phonetic: '/bred/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'My mother makes fresh bread every morning.', sentenceCn: '我妈妈每天早上做新鲜面包。' },
  { word: 'cake', translation: '蛋糕', phonetic: '/keɪk/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'We eat cake on my birthday.', sentenceCn: '我生日那天我们吃蛋糕。' },
  { word: 'water', translation: '水', phonetic: '/ˈwɔːtər/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'Please drink more water when it is hot.', sentenceCn: '天热的时候请多喝水。' },
  { word: 'juice', translation: '果汁', phonetic: '/dʒuːs/', difficulty: 1, gradeLevel: 1, theme: 'food' , sentence: 'Orange juice is my favorite drink.', sentenceCn: '橙汁是我最喜欢的饮料。' },
  { word: 'candy', translation: '糖果', phonetic: '/ˈkændi/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'Too much candy is not good for your teeth.', sentenceCn: '吃太多糖对你的牙齿不好。' },
  { word: 'orange', translation: '橙子', phonetic: '/ˈɔːrɪndʒ/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'I peel an orange and share it with my friend.', sentenceCn: '我剥一个橙子和朋友分享。' },
  { word: 'grape', translation: '葡萄', phonetic: '/ɡreɪp/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'These purple grapes are sweet and juicy.', sentenceCn: '这些紫葡萄又甜又多汁。' },
  { word: 'noodle', translation: '面条', phonetic: '/ˈnuːdəl/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'I like to eat noodles with soup.', sentenceCn: '我喜欢吃汤面。' },
  { word: 'chicken', translation: '鸡肉', phonetic: '/ˈtʃɪkɪn/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'My grandma keeps chickens in her yard.', sentenceCn: '我奶奶在院子里养鸡。' },
  { word: 'soup', translation: '汤', phonetic: '/suːp/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'Hot soup is perfect on a cold winter day.', sentenceCn: '热汤在寒冷的冬天很合适。' },
  { word: 'cookie', translation: '饼干', phonetic: '/ˈkʊki/', difficulty: 2, gradeLevel: 2, theme: 'food' , sentence: 'My grandmother bakes the best chocolate cookies.', sentenceCn: '我奶奶烤的巧克力饼干最好吃。' },
  { word: 'ice cream', translation: '冰淇淋', phonetic: '/aɪs kriːm/', difficulty: 3, gradeLevel: 2, theme: 'food' , sentence: 'I like to eat ice cream in the summer.', sentenceCn: '我喜欢在夏天吃冰淇淋。' },
  { word: 'hamburger', translation: '汉堡', phonetic: '/ˈhæmbɜːrɡər/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'He ordered a hamburger and some fries.', sentenceCn: '他点了一个汉堡和一些薯条。' },
  { word: 'pizza', translation: '披萨', phonetic: '/ˈpiːtsə/', difficulty: 2, gradeLevel: 3, theme: 'food' , sentence: 'Let us order a big pizza for dinner.', sentenceCn: '我们晚饭点一个大披萨吧。' },
  { word: 'sandwich', translation: '三明治', phonetic: '/ˈsænwɪtʃ/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'I made a cheese sandwich for my lunch.', sentenceCn: '我午餐做了一个奶酪三明治。' },
  { word: 'chocolate', translation: '巧克力', phonetic: '/ˈtʃɑːklət/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'A little chocolate makes me feel happy.', sentenceCn: '吃一点巧克力让我感到快乐。' },
  { word: 'vegetable', translation: '蔬菜', phonetic: '/ˈvedʒtəbəl/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'You should eat more green vegetables.', sentenceCn: '你应该多吃绿色蔬菜。' },
  { word: 'tomato', translation: '番茄', phonetic: '/təˈmeɪtoʊ/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'Tomatoes are red and full of vitamins.', sentenceCn: '番茄是红色的，富含维生素。' },
  { word: 'potato', translation: '土豆', phonetic: '/pəˈteɪtoʊ/', difficulty: 3, gradeLevel: 3, theme: 'food' , sentence: 'We can make chips from fresh potatoes.', sentenceCn: '我们可以用新鲜土豆做薯片。' },
  { word: 'carrot', translation: '胡萝卜', phonetic: '/ˈkærət/', difficulty: 2, gradeLevel: 3, theme: 'food' , sentence: 'Rabbits love to eat fresh carrots.', sentenceCn: '兔子喜欢吃新鲜的胡萝卜。' },
  { word: 'watermelon', translation: '西瓜', phonetic: '/ˈwɔːtərmelən/', difficulty: 4, gradeLevel: 3, theme: 'food' , sentence: 'We share a big watermelon in the hot sun.', sentenceCn: '我们在烈日下分享一个大西瓜。' },
  { word: 'strawberry', translation: '草莓', phonetic: '/ˈstrɔːberi/', difficulty: 4, gradeLevel: 3, theme: 'food' , sentence: 'The strawberry is red, sweet, and juicy.', sentenceCn: '草莓又红又甜又多汁。' },
  { word: 'pineapple', translation: '菠萝', phonetic: '/ˈpaɪnæpəl/', difficulty: 4, gradeLevel: 4, theme: 'food' , sentence: 'Cutting a pineapple takes some practice.', sentenceCn: '切菠萝需要一些练习。' },
  { word: 'mango', translation: '芒果', phonetic: '/ˈmæŋɡoʊ/', difficulty: 2, gradeLevel: 4, theme: 'food' , sentence: 'A ripe mango tastes very sweet and soft.', sentenceCn: '熟透的芒果吃起来又甜又软。' },
  { word: 'lemon', translation: '柠檬', phonetic: '/ˈlemən/', difficulty: 2, gradeLevel: 4, theme: 'food' , sentence: 'A lemon is sour, but I like its taste.', sentenceCn: '柠檬很酸，但我喜欢它的味道。' },
  { word: 'peach', translation: '桃子', phonetic: '/piːtʃ/', difficulty: 2, gradeLevel: 4, theme: 'food' , sentence: 'The peach is soft and smells very sweet.', sentenceCn: '桃子很软，闻起来很甜。' },
  { word: 'cherry', translation: '樱桃', phonetic: '/ˈtʃeri/', difficulty: 2, gradeLevel: 4, theme: 'food' , sentence: 'Cherries are small, round, and bright red.', sentenceCn: '樱桃又小又圆，颜色鲜红。' },
  { word: 'cucumber', translation: '黄瓜', phonetic: '/ˈkjuːkʌmbər/', difficulty: 4, gradeLevel: 4, theme: 'food' , sentence: 'I put cucumber slices in my salad.', sentenceCn: '我把黄瓜片放进沙拉里。' },
  { word: 'onion', translation: '洋葱', phonetic: '/ˈʌnjən/', difficulty: 2, gradeLevel: 4, theme: 'food' , sentence: 'Cutting onions makes my eyes water.', sentenceCn: '切洋葱让我的眼睛流泪。' },
  { word: 'garlic', translation: '大蒜', phonetic: '/ˈɡɑːrlɪk/', difficulty: 3, gradeLevel: 4, theme: 'food' , sentence: 'Garlic adds a strong flavor to many dishes.', sentenceCn: '大蒜给很多菜增添浓郁的风味。' },
  { word: 'mushroom', translation: '蘑菇', phonetic: '/ˈmʌʃruːm/', difficulty: 3, gradeLevel: 4, theme: 'food' , sentence: 'Mushrooms grow in the forest after rain.', sentenceCn: '雨后蘑菇在森林里生长。' },
  { word: 'sausage', translation: '香肠', phonetic: '/ˈsɔːsɪdʒ/', difficulty: 3, gradeLevel: 5, theme: 'food' , sentence: 'Grilled sausages smell really good.', sentenceCn: '烤香肠闻起来真香。' },
  { word: 'steak', translation: '牛排', phonetic: '/steɪk/', difficulty: 2, gradeLevel: 5, theme: 'food' , sentence: 'My dad knows how to cook a perfect steak.', sentenceCn: '我爸爸知道怎么煎出完美的牛排。' },
  { word: 'salad', translation: '沙拉', phonetic: '/ˈsæləd/', difficulty: 2, gradeLevel: 5, theme: 'food' , sentence: 'A fresh salad is a healthy choice for lunch.', sentenceCn: '新鲜的沙拉是健康的午餐选择。' },
  { word: 'cheese', translation: '奶酪', phonetic: '/tʃiːz/', difficulty: 2, gradeLevel: 5, theme: 'food' , sentence: 'I like to put cheese on my bread.', sentenceCn: '我喜欢在面包上放奶酪。' },
  { word: 'butter', translation: '黄油', phonetic: '/ˈbʌtər/', difficulty: 2, gradeLevel: 5, theme: 'food' , sentence: 'Spread some butter on the warm toast.', sentenceCn: '在热吐司上涂一些黄油。' },
  { word: 'yogurt', translation: '酸奶', phonetic: '/ˈjoʊɡərt/', difficulty: 3, gradeLevel: 5, theme: 'food' , sentence: 'Yogurt with fruit makes a great snack.', sentenceCn: '加水果的酸奶是很棒的零食。' },
  { word: 'cereal', translation: '麦片', phonetic: '/ˈsɪriəl/', difficulty: 3, gradeLevel: 5, theme: 'food' , sentence: 'I eat cereal with milk for breakfast.', sentenceCn: '我早餐吃麦片配牛奶。' },
  { word: 'pumpkin', translation: '南瓜', phonetic: '/ˈpʌmpkɪn/', difficulty: 3, gradeLevel: 5, theme: 'food' , sentence: 'We carve a pumpkin for Halloween every year.', sentenceCn: '我们每年为万圣节刻一个南瓜。' },
  { word: 'corn', translation: '玉米', phonetic: '/kɔːrn/', difficulty: 2, gradeLevel: 5, theme: 'food' , sentence: 'Corn grows tall in the field in summer.', sentenceCn: '夏天玉米在田里长得很高。' },
  { word: 'delicious', translation: '美味的', phonetic: '/dɪˈlɪʃəs/', difficulty: 3, gradeLevel: 5, theme: 'food' , sentence: 'This cake is the most delicious I have ever had.', sentenceCn: '这个蛋糕是我吃过最好吃的。' },
  { word: 'cuisine', translation: '菜肴', phonetic: '/kwɪˈziːn/', difficulty: 5, gradeLevel: 6, theme: 'food' , sentence: 'Chinese cuisine is famous all over the world.', sentenceCn: '中国菜肴在全世界都很有名。' },
  { word: 'recipe', translation: '食谱', phonetic: '/ˈresəpi/', difficulty: 4, gradeLevel: 6, theme: 'food' , sentence: 'My mother shared her secret recipe with me.', sentenceCn: '妈妈把她的秘密食谱分享给了我。' },
  { word: 'ingredient', translation: '食材', phonetic: '/ɪnˈɡriːdiənt/', difficulty: 5, gradeLevel: 6, theme: 'food' , sentence: 'Flour is the main ingredient for bread.', sentenceCn: '面粉是做面包的主要食材。' },
  { word: 'flavor', translation: '风味', phonetic: '/ˈfleɪvər/', difficulty: 4, gradeLevel: 6, theme: 'food' , sentence: 'This soup has a very rich and warm flavor.', sentenceCn: '这汤有很浓郁温暖的风味。' },
  { word: 'nutrition', translation: '营养', phonetic: '/nuːˈtrɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'food' , sentence: 'Good nutrition helps children grow strong.', sentenceCn: '好的营养帮助孩子长得强壮。' },
  { word: 'appetite', translation: '食欲', phonetic: '/ˈæpətaɪt/', difficulty: 5, gradeLevel: 6, theme: 'food' , sentence: 'Running outside gives me a big appetite.', sentenceCn: '在外面跑步让我胃口大开。' },
  { word: 'snack', translation: '零食', phonetic: '/snæk/', difficulty: 2, gradeLevel: 6, theme: 'food' , sentence: 'I bring a healthy snack to school each day.', sentenceCn: '我每天带一份健康零食去学校。' },
  { word: 'feast', translation: '盛宴', phonetic: '/fiːst/', difficulty: 4, gradeLevel: 6, theme: 'food' , sentence: 'The family prepared a feast for the holiday.', sentenceCn: '全家人为节日准备了一场盛宴。' },
  { word: 'dessert', translation: '甜点', phonetic: '/dɪˈzɜːrt/', difficulty: 4, gradeLevel: 6, theme: 'food' , sentence: 'For dessert, we had ice cream and cake.', sentenceCn: '甜点我们吃了冰淇淋和蛋糕。' },
  { word: 'head', translation: '头', phonetic: '/hed/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'Please wear a hat to protect your head.', sentenceCn: '请戴帽子保护你的头。' },
  { word: 'hand', translation: '手', phonetic: '/hænd/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'Wash your hands before eating.', sentenceCn: '吃饭前要洗手。' },
  { word: 'eye', translation: '眼睛', phonetic: '/aɪ/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'Close your eyes and make a wish.', sentenceCn: '闭上眼睛许个愿。' },
  { word: 'ear', translation: '耳朵', phonetic: '/ɪr/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'Rabbits have long ears to hear well.', sentenceCn: '兔子有长耳朵来听声音。' },
  { word: 'nose', translation: '鼻子', phonetic: '/noʊz/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'I can smell flowers with my nose.', sentenceCn: '我用鼻子闻花香。' },
  { word: 'mouth', translation: '嘴巴', phonetic: '/maʊθ/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'Open your mouth and say ah.', sentenceCn: '张开嘴巴说啊。' },
  { word: 'face', translation: '脸', phonetic: '/feɪs/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'She washed her face with cold water.', sentenceCn: '她用冷水洗了脸。' },
  { word: 'arm', translation: '手臂', phonetic: '/ɑːrm/', difficulty: 1, gradeLevel: 2, theme: 'body' , sentence: 'She carries the baby in her arms.', sentenceCn: '她把宝宝抱在怀里。' },
  { word: 'leg', translation: '腿', phonetic: '/leɡ/', difficulty: 1, gradeLevel: 2, theme: 'body' , sentence: 'He has long legs and runs very fast.', sentenceCn: '他有长腿，跑得非常快。' },
  { word: 'foot', translation: '脚', phonetic: '/fʊt/', difficulty: 1, gradeLevel: 2, theme: 'body' , sentence: 'I hurt my left foot when playing soccer.', sentenceCn: '我踢足球时伤了左脚。' },
  { word: 'hair', translation: '头发', phonetic: '/her/', difficulty: 1, gradeLevel: 2, theme: 'body' , sentence: 'She has long, shiny black hair.', sentenceCn: '她有一头又长又亮的黑发。' },
  { word: 'tooth', translation: '牙齿', phonetic: '/tuːθ/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'Brush your tooth two times every day.', sentenceCn: '每天刷两次牙。' },
  { word: 'finger', translation: '手指', phonetic: '/ˈfɪŋɡər/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'I cut my finger while cutting paper.', sentenceCn: '我裁纸的时候割伤了手指。' },
  { word: 'knee', translation: '膝盖', phonetic: '/niː/', difficulty: 2, gradeLevel: 3, theme: 'body' , sentence: 'He fell down and hurt his knee.', sentenceCn: '他摔倒了，伤了膝盖。' },
  { word: 'shoulder', translation: '肩膀', phonetic: '/ˈʃoʊldər/', difficulty: 3, gradeLevel: 3, theme: 'body' , sentence: 'He put a hand on my shoulder and smiled.', sentenceCn: '他把手放在我肩膀上笑了笑。' },
  { word: 'neck', translation: '脖子', phonetic: '/nek/', difficulty: 2, gradeLevel: 3, theme: 'body' , sentence: 'Giraffes are known for their very long necks.', sentenceCn: '长颈鹿以长脖子而闻名。' },
  { word: 'tongue', translation: '舌头', phonetic: '/tʌŋ/', difficulty: 2, gradeLevel: 3, theme: 'body' , sentence: 'The ice cream feels cold on my tongue.', sentenceCn: '冰淇淋在我舌头上感觉很凉。' },
  { word: 'stomach', translation: '肚子', phonetic: '/ˈstʌmək/', difficulty: 3, gradeLevel: 3, theme: 'body' , sentence: 'My stomach hurts because I ate too much.', sentenceCn: '我肚子疼，因为吃太多了。' },
  { word: 'elbow', translation: '肘部', phonetic: '/ˈelboʊ/', difficulty: 3, gradeLevel: 4, theme: 'body' , sentence: 'He bumped his elbow on the door.', sentenceCn: '他的肘部撞到了门上。' },
  { word: 'wrist', translation: '手腕', phonetic: '/rɪst/', difficulty: 3, gradeLevel: 4, theme: 'body' , sentence: 'She wears a pretty watch on her wrist.', sentenceCn: '她手腕上戴着一只漂亮的手表。' },
  { word: 'ankle', translation: '脚踝', phonetic: '/ˈæŋkəl/', difficulty: 3, gradeLevel: 4, theme: 'body' , sentence: 'I twisted my ankle while playing soccer.', sentenceCn: '我踢足球时扭伤了脚踝。' },
  { word: 'thumb', translation: '拇指', phonetic: '/θʌm/', difficulty: 3, gradeLevel: 4, theme: 'body' , sentence: 'Give a thumbs up if you like the idea.', sentenceCn: '如果你喜欢这个主意就竖起拇指。' },
  { word: 'brain', translation: '大脑', phonetic: '/breɪn/', difficulty: 3, gradeLevel: 4, theme: 'body' , sentence: 'The brain helps us think and learn new things.', sentenceCn: '大脑帮助我们思考和学习新东西。' },
  { word: 'heart', translation: '心脏', phonetic: '/hɑːrt/', difficulty: 2, gradeLevel: 4, theme: 'body' , sentence: 'Exercise is good for your heart and body.', sentenceCn: '锻炼对你的心脏和身体都有好处。' },
  { word: 'muscle', translation: '肌肉', phonetic: '/ˈmʌsəl/', difficulty: 3, gradeLevel: 5, theme: 'body' , sentence: 'Running helps build strong leg muscles.', sentenceCn: '跑步有助于练出强壮的腿部肌肉。' },
  { word: 'bone', translation: '骨头', phonetic: '/boʊn/', difficulty: 2, gradeLevel: 5, theme: 'body' , sentence: 'Milk helps make your bones strong.', sentenceCn: '牛奶有助于让你的骨骼强壮。' },
  { word: 'skin', translation: '皮肤', phonetic: '/skɪn/', difficulty: 2, gradeLevel: 5, theme: 'body' , sentence: 'Put on sunscreen to protect your skin.', sentenceCn: '涂上防晒霜来保护你的皮肤。' },
  { word: 'blood', translation: '血液', phonetic: '/blʌd/', difficulty: 2, gradeLevel: 5, theme: 'body' , sentence: 'Your heart pumps blood all through your body.', sentenceCn: '你的心脏把血液输送到全身。' },
  { word: 'lung', translation: '肺', phonetic: '/lʌŋ/', difficulty: 3, gradeLevel: 5, theme: 'body' , sentence: 'Our lungs help us breathe in fresh air.', sentenceCn: '我们的肺帮我们呼吸新鲜空气。' },
  { word: 'spine', translation: '脊椎', phonetic: '/spaɪn/', difficulty: 4, gradeLevel: 5, theme: 'body' , sentence: 'Sit up straight to protect your spine.', sentenceCn: '坐直来保护你的脊椎。' },
  { word: 'skeleton', translation: '骨骼', phonetic: '/ˈskelɪtən/', difficulty: 4, gradeLevel: 6, theme: 'body' , sentence: 'The skeleton gives our body its shape.', sentenceCn: '骨骼赋予我们的身体形状。' },
  { word: 'organ', translation: '器官', phonetic: '/ˈɔːrɡən/', difficulty: 4, gradeLevel: 6, theme: 'body' , sentence: 'The heart is a very important organ.', sentenceCn: '心脏是一个非常重要的器官。' },
  { word: 'nerve', translation: '神经', phonetic: '/nɜːrv/', difficulty: 4, gradeLevel: 6, theme: 'body' , sentence: 'Nerves send messages from your brain to your body.', sentenceCn: '神经将信息从大脑传递到全身。' },
  { word: 'digest', translation: '消化', phonetic: '/daɪˈdʒest/', difficulty: 4, gradeLevel: 6, theme: 'body' , sentence: 'It takes time for your body to digest food.', sentenceCn: '身体消化食物需要时间。' },
  { word: 'breathe', translation: '呼吸', phonetic: '/briːð/', difficulty: 3, gradeLevel: 6, theme: 'body' , sentence: 'Take a deep breath and relax your body.', sentenceCn: '深呼吸，放松身体。' },
  { word: 'sense', translation: '感官', phonetic: '/sens/', difficulty: 3, gradeLevel: 6, theme: 'body' , sentence: 'Dogs have a very strong sense of smell.', sentenceCn: '狗有非常强的嗅觉。' },
  { word: 'height', translation: '身高', phonetic: '/haɪt/', difficulty: 2, gradeLevel: 6, theme: 'body' , sentence: 'What is your height? I am 130 centimeters tall.', sentenceCn: '你身高多少？我130厘米。' },
  { word: 'weight', translation: '体重', phonetic: '/weɪt/', difficulty: 2, gradeLevel: 6, theme: 'body' , sentence: 'The doctor checked my weight and height.', sentenceCn: '医生检查了我的体重和身高。' },
  { word: 'healthy', translation: '健康的', phonetic: '/ˈhelθi/', difficulty: 2, gradeLevel: 6, theme: 'body' , sentence: 'Eating fruits and vegetables keeps us healthy.', sentenceCn: '吃水果蔬菜让我们保持健康。' },
  { word: 'strong', translation: '强壮的', phonetic: '/strɒŋ/', difficulty: 2, gradeLevel: 6, theme: 'body' , sentence: 'He is very strong and can lift heavy things.', sentenceCn: '他很强壮，能举起很重的东西。' },
  { word: 'red', translation: '红色', phonetic: '/red/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'The red apple looks very delicious.', sentenceCn: '红色的苹果看起来很美味。' },
  { word: 'blue', translation: '蓝色', phonetic: '/bluː/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'The sky is blue and the sun is shining.', sentenceCn: '天空是蓝色的，阳光灿烂。' },
  { word: 'yellow', translation: '黄色', phonetic: '/ˈjeloʊ/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'Yellow flowers bloom in the spring.', sentenceCn: '黄色的花在春天开放。' },
  { word: 'green', translation: '绿色', phonetic: '/ɡriːn/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'The green grass feels soft under my feet.', sentenceCn: '绿色的草在脚下感觉很柔软。' },
  { word: 'white', translation: '白色', phonetic: '/waɪt/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'Snow is white and covers the ground.', sentenceCn: '雪是白色的，覆盖着大地。' },
  { word: 'black', translation: '黑色', phonetic: '/blæk/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'I have a black cat with green eyes.', sentenceCn: '我有一只绿眼睛的黑猫。' },
  { word: 'pink', translation: '粉色', phonetic: '/pɪŋk/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'She wears a pretty pink dress today.', sentenceCn: '她今天穿了一条漂亮的粉色裙子。' },
  { word: 'purple', translation: '紫色', phonetic: '/ˈpɜːrpəl/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'Purple is the color of magic and dreams.', sentenceCn: '紫色是魔法和梦想的颜色。' },
  { word: 'orange', translation: '橙色', phonetic: '/ˈɔːrɪndʒ/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'The orange sunset looks beautiful.', sentenceCn: '橙色的日落看起来很美丽。' },
  { word: 'brown', translation: '棕色', phonetic: '/braʊn/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'The brown dog is sleeping under the table.', sentenceCn: '棕色的狗在桌子下面睡觉。' },
  { word: 'grey', translation: '灰色', phonetic: '/ɡreɪ/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'The sky is grey before it starts to rain.', sentenceCn: '下雨前天空是灰色的。' },
  { word: 'gold', translation: '金色', phonetic: '/ɡoʊld/', difficulty: 2, gradeLevel: 3, theme: 'color' , sentence: 'She wore a shiny gold necklace.', sentenceCn: '她戴了一条闪亮的金色项链。' },
  { word: 'silver', translation: '银色', phonetic: '/ˈsɪlvər/', difficulty: 2, gradeLevel: 3, theme: 'color' , sentence: 'The moon shines with a soft silver light.', sentenceCn: '月亮发出柔和的银色光芒。' },
  { word: 'light', translation: '浅色的', phonetic: '/laɪt/', difficulty: 2, gradeLevel: 3, theme: 'color' , sentence: 'I like light blue more than dark blue.', sentenceCn: '比起深蓝色，我更喜欢浅蓝色。' },
  { word: 'dark', translation: '深色的', phonetic: '/dɑːrk/', difficulty: 2, gradeLevel: 3, theme: 'color' , sentence: 'It is too dark in here, turn on the light.', sentenceCn: '这里太暗了，开灯吧。' },
  { word: 'bright', translation: '明亮的', phonetic: '/braɪt/', difficulty: 2, gradeLevel: 3, theme: 'color' , sentence: 'The bright sun made me close my eyes.', sentenceCn: '明亮的太阳让我闭上了眼睛。' },
  { word: 'rainbow', translation: '彩虹', phonetic: '/ˈreɪnboʊ/', difficulty: 3, gradeLevel: 3, theme: 'color' , sentence: 'After the rain, a rainbow appeared in the sky.', sentenceCn: '雨后，天空中出现了彩虹。' },
  { word: 'colorful', translation: '多彩的', phonetic: '/ˈkʌlərfəl/', difficulty: 3, gradeLevel: 4, theme: 'color' , sentence: 'The garden is full of colorful flowers.', sentenceCn: '花园里开满了五颜六色的花。' },
  { word: 'pale', translation: '苍白的', phonetic: '/peɪl/', difficulty: 3, gradeLevel: 4, theme: 'color' , sentence: 'She looked pale, so I asked if she was okay.', sentenceCn: '她脸色苍白，我问她还好吗。' },
  { word: 'violet', translation: '紫罗兰色', phonetic: '/ˈvaɪələt/', difficulty: 3, gradeLevel: 4, theme: 'color' , sentence: 'Violet flowers bloom in the early spring.', sentenceCn: '紫罗兰色的花在早春开放。' },
  { word: 'indigo', translation: '靛蓝色', phonetic: '/ˈɪndɪɡoʊ/', difficulty: 4, gradeLevel: 5, theme: 'color' , sentence: 'Indigo is a deep color between blue and purple.', sentenceCn: '靛蓝色是介于蓝色和紫色之间的深色。' },
  { word: 'crimson', translation: '深红色', phonetic: '/ˈkrɪmzən/', difficulty: 4, gradeLevel: 5, theme: 'color' , sentence: 'The crimson leaves fall in autumn.', sentenceCn: '深红色的叶子在秋天飘落。' },
  { word: 'scarlet', translation: '猩红色', phonetic: '/ˈskɑːrlət/', difficulty: 4, gradeLevel: 5, theme: 'color' , sentence: 'She wore a scarlet dress to the party.', sentenceCn: '她穿了一条猩红色的裙子去聚会。' },
  { word: 'amber', translation: '琥珀色', phonetic: '/ˈæmbər/', difficulty: 4, gradeLevel: 5, theme: 'color' , sentence: 'The amber light of the sunset filled the room.', sentenceCn: '琥珀色的夕阳余晖洒满房间。' },
  { word: 'turquoise', translation: '绿松色', phonetic: '/ˈtɜːrkwɔɪz/', difficulty: 5, gradeLevel: 6, theme: 'color' , sentence: 'The sea water is a beautiful turquoise color.', sentenceCn: '海水是美丽的绿松色。' },
  { word: 'coral', translation: '珊瑚色', phonetic: '/ˈkɔːrəl/', difficulty: 4, gradeLevel: 6, theme: 'color' , sentence: 'The coral reef is full of colorful fish.', sentenceCn: '珊瑚礁里满是五颜六色的鱼。' },
  { word: 'navy', translation: '海军蓝', phonetic: '/ˈneɪvi/', difficulty: 4, gradeLevel: 6, theme: 'color' , sentence: 'He wore a navy blue jacket to school.', sentenceCn: '他穿了一件海军蓝的夹克去上学。' },
  { word: 'beige', translation: '米色', phonetic: '/beɪʒ/', difficulty: 4, gradeLevel: 6, theme: 'color' , sentence: 'The walls in my room are painted beige.', sentenceCn: '我房间的墙壁刷成了米色。' },
  { word: 'shade', translation: '色调', phonetic: '/ʃeɪd/', difficulty: 3, gradeLevel: 6, theme: 'color' , sentence: 'We sat in the shade under the big tree.', sentenceCn: '我们坐在大树的树荫下。' },
  { word: 'transparent', translation: '透明的', phonetic: '/trænsˈpærənt/', difficulty: 5, gradeLevel: 6, theme: 'color' , sentence: 'The window glass is clean and transparent.', sentenceCn: '窗户玻璃干净透明。' },
  { word: 'sun', translation: '太阳', phonetic: '/sʌn/', difficulty: 1, gradeLevel: 1, theme: 'weather' , sentence: 'The sun gives us light and warmth.', sentenceCn: '太阳给我们光和温暖。' },
  { word: 'rain', translation: '雨', phonetic: '/reɪn/', difficulty: 1, gradeLevel: 1, theme: 'weather' , sentence: 'It is raining outside, take an umbrella.', sentenceCn: '外面在下雨，带把伞。' },
  { word: 'snow', translation: '雪', phonetic: '/snoʊ/', difficulty: 1, gradeLevel: 1, theme: 'weather' , sentence: 'Children love to play in the snow.', sentenceCn: '孩子们喜欢在雪地里玩。' },
  { word: 'wind', translation: '风', phonetic: '/wɪnd/', difficulty: 1, gradeLevel: 1, theme: 'weather' , sentence: 'The wind blows the leaves off the trees.', sentenceCn: '风把树叶吹落了。' },
  { word: 'cloud', translation: '云', phonetic: '/klaʊd/', difficulty: 1, gradeLevel: 1, theme: 'weather' , sentence: 'Look at that cloud, it looks like a rabbit!', sentenceCn: '看那朵云，像一只兔子！' },
  { word: 'hot', translation: '炎热的', phonetic: '/hɑːt/', difficulty: 1, gradeLevel: 2, theme: 'weather' , sentence: 'It is very hot today, let us drink some water.', sentenceCn: '今天很热，我们喝点水吧。' },
  { word: 'cold', translation: '寒冷的', phonetic: '/koʊld/', difficulty: 1, gradeLevel: 2, theme: 'weather' , sentence: 'Wear your coat, it is very cold outside.', sentenceCn: '穿上外套，外面很冷。' },
  { word: 'warm', translation: '温暖的', phonetic: '/wɔːrm/', difficulty: 1, gradeLevel: 2, theme: 'weather' , sentence: 'The warm sun feels nice on my face.', sentenceCn: '温暖的阳光照在脸上很舒服。' },
  { word: 'cool', translation: '凉爽的', phonetic: '/kuːl/', difficulty: 1, gradeLevel: 2, theme: 'weather' , sentence: 'A cool breeze blew through the open window.', sentenceCn: '一阵凉爽的风从开着的窗户吹进来。' },
  { word: 'sunny', translation: '晴朗的', phonetic: '/ˈsʌni/', difficulty: 2, gradeLevel: 2, theme: 'weather' , sentence: 'It is a bright and sunny day, let us go out.', sentenceCn: '今天阳光明媚，我们出去吧。' },
  { word: 'rainy', translation: '下雨的', phonetic: '/ˈreɪni/', difficulty: 2, gradeLevel: 2, theme: 'weather' , sentence: 'On rainy days, I like to read at home.', sentenceCn: '下雨天我喜欢在家看书。' },
  { word: 'cloudy', translation: '多云的', phonetic: '/ˈklaʊdi/', difficulty: 2, gradeLevel: 2, theme: 'weather' , sentence: 'The sky is cloudy, it might rain soon.', sentenceCn: '天空多云，可能很快要下雨了。' },
  { word: 'windy', translation: '有风的', phonetic: '/ˈwɪndi/', difficulty: 2, gradeLevel: 2, theme: 'weather' , sentence: 'It is too windy to fly a kite today.', sentenceCn: '今天风太大，不适合放风筝。' },
  { word: 'snowy', translation: '下雪的', phonetic: '/ˈsnoʊi/', difficulty: 2, gradeLevel: 2, theme: 'weather' , sentence: 'We made a snowman on that snowy morning.', sentenceCn: '在那个下雪的早晨我们堆了一个雪人。' },
  { word: 'storm', translation: '暴风雨', phonetic: '/stɔːrm/', difficulty: 2, gradeLevel: 3, theme: 'weather' , sentence: 'A big storm is coming, we should stay inside.', sentenceCn: '大暴风雨要来了，我们应该待在屋里。' },
  { word: 'thunder', translation: '雷声', phonetic: '/ˈθʌndər/', difficulty: 3, gradeLevel: 3, theme: 'weather' , sentence: 'The loud thunder scared my little dog.', sentenceCn: '巨大的雷声吓到了我的小狗。' },
  { word: 'lightning', translation: '闪电', phonetic: '/ˈlaɪtnɪŋ/', difficulty: 3, gradeLevel: 3, theme: 'weather' , sentence: 'I saw lightning flash across the dark sky.', sentenceCn: '我看到闪电划过黑暗的天空。' },
  { word: 'fog', translation: '雾', phonetic: '/fɒɡ/', difficulty: 2, gradeLevel: 3, theme: 'weather' , sentence: 'The thick fog made it hard to see the road.', sentenceCn: '浓雾让道路很难看清。' },
  { word: 'rainbow', translation: '彩虹', phonetic: '/ˈreɪnboʊ/', difficulty: 3, gradeLevel: 3, theme: 'weather' , sentence: 'After the rain, a rainbow appeared in the sky.', sentenceCn: '雨后，天空中出现了彩虹。' },
  { word: 'temperature', translation: '温度', phonetic: '/ˈtemprətʃər/', difficulty: 4, gradeLevel: 4, theme: 'weather' , sentence: 'The temperature today is thirty degrees.', sentenceCn: '今天的气温是三十度。' },
  { word: 'freeze', translation: '结冰', phonetic: '/friːz/', difficulty: 3, gradeLevel: 4, theme: 'weather' , sentence: 'Water will freeze when it is very cold.', sentenceCn: '天气很冷的时候水会结冰。' },
  { word: 'melt', translation: '融化', phonetic: '/melt/', difficulty: 3, gradeLevel: 4, theme: 'weather' , sentence: 'The snow began to melt in the warm sun.', sentenceCn: '雪在温暖的阳光下开始融化。' },
  { word: 'breeze', translation: '微风', phonetic: '/briːz/', difficulty: 3, gradeLevel: 4, theme: 'weather' , sentence: 'A gentle breeze made the leaves dance.', sentenceCn: '一阵微风让树叶跳起舞来。' },
  { word: 'humidity', translation: '湿度', phonetic: '/hjuːˈmɪdəti/', difficulty: 5, gradeLevel: 5, theme: 'weather' , sentence: 'The high humidity makes the air feel heavy.', sentenceCn: '高湿度让空气感觉很闷。' },
  { word: 'forecast', translation: '预报', phonetic: '/ˈfɔːrkæst/', difficulty: 4, gradeLevel: 5, theme: 'weather' , sentence: 'The weather forecast says it will rain tomorrow.', sentenceCn: '天气预报说明天会下雨。' },
  { word: 'climate', translation: '气候', phonetic: '/ˈklaɪmət/', difficulty: 4, gradeLevel: 5, theme: 'weather' , sentence: 'The climate here is warm all year round.', sentenceCn: '这里的气候全年都很温暖。' },
  { word: 'drought', translation: '干旱', phonetic: '/draʊt/', difficulty: 4, gradeLevel: 6, theme: 'weather' , sentence: 'The long drought dried up all the rivers.', sentenceCn: '漫长的干旱让所有的河都干涸了。' },
  { word: 'flood', translation: '洪水', phonetic: '/flʌd/', difficulty: 3, gradeLevel: 6, theme: 'weather' , sentence: 'Heavy rain caused a flood in the village.', sentenceCn: '大雨在村庄里引发了洪水。' },
  { word: 'hurricane', translation: '飓风', phonetic: '/ˈhɜːrəkeɪn/', difficulty: 5, gradeLevel: 6, theme: 'weather' , sentence: 'A hurricane can bring very strong winds.', sentenceCn: '飓风会带来非常强的风。' },
  { word: 'blizzard', translation: '暴风雪', phonetic: '/ˈblɪzərd/', difficulty: 5, gradeLevel: 6, theme: 'weather' , sentence: 'The blizzard covered the town in deep snow.', sentenceCn: '暴风雪把整个镇子埋在深深的雪里。' },
  { word: 'run', translation: '跑步', phonetic: '/rʌn/', difficulty: 1, gradeLevel: 1, theme: 'sports' , sentence: 'I run in the park every morning.', sentenceCn: '我每天早上在公园跑步。' },
  { word: 'jump', translation: '跳', phonetic: '/dʒʌmp/', difficulty: 1, gradeLevel: 1, theme: 'sports' , sentence: 'The rabbit can jump very high.', sentenceCn: '兔子能跳得很高。' },
  { word: 'swim', translation: '游泳', phonetic: '/swɪm/', difficulty: 1, gradeLevel: 1, theme: 'sports' , sentence: 'Let us go swimming in the pool.', sentenceCn: '我们去游泳池游泳吧。' },
  { word: 'play', translation: '玩', phonetic: '/pleɪ/', difficulty: 1, gradeLevel: 1, theme: 'sports' , sentence: 'Come and play with us in the park.', sentenceCn: '来公园和我们一起玩吧。' },
  { word: 'ball', translation: '球', phonetic: '/bɔːl/', difficulty: 1, gradeLevel: 1, theme: 'sports' , sentence: 'Kick the ball to me, please.', sentenceCn: '请把球踢给我。' },
  { word: 'walk', translation: '散步', phonetic: '/wɔːk/', difficulty: 1, gradeLevel: 2, theme: 'sports' , sentence: 'Let us take a walk after dinner.', sentenceCn: '晚饭后我们去散个步吧。' },
  { word: 'dance', translation: '跳舞', phonetic: '/dæns/', difficulty: 1, gradeLevel: 2, theme: 'sports' , sentence: 'She loves to dance to the music.', sentenceCn: '她喜欢跟着音乐跳舞。' },
  { word: 'ride', translation: '骑', phonetic: '/raɪd/', difficulty: 1, gradeLevel: 2, theme: 'sports' , sentence: 'I want to learn how to ride a horse.', sentenceCn: '我想学骑马。' },
  { word: 'kick', translation: '踢', phonetic: '/kɪk/', difficulty: 2, gradeLevel: 2, theme: 'sports' , sentence: 'He can kick the ball very far.', sentenceCn: '他能把球踢得很远。' },
  { word: 'throw', translation: '扔', phonetic: '/θroʊ/', difficulty: 2, gradeLevel: 2, theme: 'sports' , sentence: 'Throw the ball to me, I will catch it.', sentenceCn: '把球扔给我，我会接住的。' },
  { word: 'catch', translation: '接住', phonetic: '/kætʃ/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'Can you catch this ball with one hand?', sentenceCn: '你能用一只手接住这个球吗？' },
  { word: 'climb', translation: '攀爬', phonetic: '/klaɪm/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'We plan to climb that mountain next week.', sentenceCn: '我们计划下周爬那座山。' },
  { word: 'skate', translation: '滑冰', phonetic: '/skeɪt/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'She learned to skate on the frozen lake.', sentenceCn: '她在结冰的湖面上学会了滑冰。' },
  { word: 'ski', translation: '滑雪', phonetic: '/skiː/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'We go to the mountains to ski in winter.', sentenceCn: '冬天我们去山里滑雪。' },
  { word: 'race', translation: '比赛', phonetic: '/reɪs/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'Who will win the running race today?', sentenceCn: '今天谁会赢得跑步比赛？' },
  { word: 'team', translation: '团队', phonetic: '/tiːm/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'We work as a team to win the game.', sentenceCn: '我们团结协作来赢得比赛。' },
  { word: 'win', translation: '赢', phonetic: '/wɪn/', difficulty: 1, gradeLevel: 3, theme: 'sports' , sentence: 'I hope our team will win the match.', sentenceCn: '我希望我们队能赢这场比赛。' },
  { word: 'football', translation: '足球', phonetic: '/ˈfʊtbɔːl/', difficulty: 3, gradeLevel: 3, theme: 'sports' , sentence: 'Playing football is his favorite hobby.', sentenceCn: '踢足球是他最喜欢的爱好。' },
  { word: 'basketball', translation: '篮球', phonetic: '/ˈbæskɪtbɔːl/', difficulty: 4, gradeLevel: 3, theme: 'sports' , sentence: 'He is very good at playing basketball.', sentenceCn: '他打篮球打得非常好。' },
  { word: 'badminton', translation: '羽毛球', phonetic: '/ˈbædmɪntən/', difficulty: 4, gradeLevel: 4, theme: 'sports' , sentence: 'We play badminton in the yard after school.', sentenceCn: '放学后我们在院子里打羽毛球。' },
  { word: 'tennis', translation: '网球', phonetic: '/ˈtenɪs/', difficulty: 3, gradeLevel: 4, theme: 'sports' , sentence: 'She takes tennis lessons every Saturday.', sentenceCn: '她每周六上网球课。' },
  { word: 'volleyball', translation: '排球', phonetic: '/ˈvɑːlibɔːl/', difficulty: 4, gradeLevel: 4, theme: 'sports' , sentence: 'Our class won the volleyball match.', sentenceCn: '我们班赢了排球比赛。' },
  { word: 'baseball', translation: '棒球', phonetic: '/ˈbeɪsbɔːl/', difficulty: 4, gradeLevel: 4, theme: 'sports' , sentence: 'Baseball is a very popular sport in America.', sentenceCn: '棒球在美国是非常受欢迎的运动。' },
  { word: 'golf', translation: '高尔夫', phonetic: '/ɡɒlf/', difficulty: 3, gradeLevel: 4, theme: 'sports' , sentence: 'My grandpa likes to play golf on weekends.', sentenceCn: '我爷爷喜欢周末打高尔夫。' },
  { word: 'exercise', translation: '锻炼', phonetic: '/ˈeksərsaɪz/', difficulty: 3, gradeLevel: 4, theme: 'sports' , sentence: 'Doing exercise every day keeps you fit.', sentenceCn: '每天锻炼让你保持健康。' },
  { word: 'stretch', translation: '拉伸', phonetic: '/stretʃ/', difficulty: 3, gradeLevel: 4, theme: 'sports' , sentence: 'Always stretch before you start to run.', sentenceCn: '开始跑步前一定要先拉伸。' },
  { word: 'marathon', translation: '马拉松', phonetic: '/ˈmærəθɑːn/', difficulty: 5, gradeLevel: 5, theme: 'sports' , sentence: 'Running a marathon takes a lot of training.', sentenceCn: '跑马拉松需要大量训练。' },
  { word: 'gymnastics', translation: '体操', phonetic: '/dʒɪmˈnæstɪks/', difficulty: 5, gradeLevel: 5, theme: 'sports' , sentence: 'She practices gymnastics three times a week.', sentenceCn: '她每周练习三次体操。' },
  { word: 'athlete', translation: '运动员', phonetic: '/ˈæθliːt/', difficulty: 4, gradeLevel: 5, theme: 'sports' , sentence: 'An athlete trains very hard every day.', sentenceCn: '运动员每天都非常努力地训练。' },
  { word: 'coach', translation: '教练', phonetic: '/koʊtʃ/', difficulty: 3, gradeLevel: 5, theme: 'sports' , sentence: 'Our coach told us to never give up.', sentenceCn: '我们的教练告诉我们永远不要放弃。' },
  { word: 'tournament', translation: '锦标赛', phonetic: '/ˈtʊrnəmənt/', difficulty: 5, gradeLevel: 5, theme: 'sports' , sentence: 'The tennis tournament starts next Monday.', sentenceCn: '网球锦标赛下周一开始。' },
  { word: 'medal', translation: '奖牌', phonetic: '/ˈmedəl/', difficulty: 3, gradeLevel: 5, theme: 'sports' , sentence: 'She won a gold medal in the swimming race.', sentenceCn: '她在游泳比赛中获得了金牌。' },
  { word: 'champion', translation: '冠军', phonetic: '/ˈtʃæmpiən/', difficulty: 4, gradeLevel: 5, theme: 'sports' , sentence: 'He became the world champion last year.', sentenceCn: '他去年成为了世界冠军。' },
  { word: 'referee', translation: '裁判', phonetic: '/ˌrefəˈriː/', difficulty: 5, gradeLevel: 6, theme: 'sports' , sentence: 'The referee blew the whistle to start the game.', sentenceCn: '裁判吹响了哨子开始比赛。' },
  { word: 'stadium', translation: '体育场', phonetic: '/ˈsteɪdiəm/', difficulty: 4, gradeLevel: 6, theme: 'sports' , sentence: 'Thousands of people came to the stadium.', sentenceCn: '成千上万的人来到了体育场。' },
  { word: 'opponent', translation: '对手', phonetic: '/əˈpoʊnənt/', difficulty: 5, gradeLevel: 6, theme: 'sports' , sentence: 'Shake hands with your opponent after the game.', sentenceCn: '比赛结束后要和对手握手。' },
  { word: 'victory', translation: '胜利', phonetic: '/ˈvɪktəri/', difficulty: 4, gradeLevel: 6, theme: 'sports' , sentence: 'The team celebrated their big victory.', sentenceCn: '球队庆祝了他们的重大胜利。' },
  { word: 'defeat', translation: '失败', phonetic: '/dɪˈfiːt/', difficulty: 4, gradeLevel: 6, theme: 'sports' , sentence: 'You learn more from defeat than from winning.', sentenceCn: '你从失败中学到的比从胜利中更多。' },
  { word: 'strategy', translation: '策略', phonetic: '/ˈstrætədʒi/', difficulty: 5, gradeLevel: 6, theme: 'sports' , sentence: 'A good strategy can help you win the game.', sentenceCn: '好的策略能帮你赢得比赛。' },
  { word: 'endurance', translation: '耐力', phonetic: '/ɪnˈdʊrəns/', difficulty: 5, gradeLevel: 6, theme: 'sports' , sentence: 'Long distance running builds great endurance.', sentenceCn: '长跑能培养很好的耐力。' },
  { word: 'mom', translation: '妈妈', phonetic: '/mɑːm/', difficulty: 1, gradeLevel: 1, theme: 'family' , sentence: 'My mom gives the best hugs in the world.', sentenceCn: '我妈妈给的拥抱是世界上最棒的。' },
  { word: 'dad', translation: '爸爸', phonetic: '/dæd/', difficulty: 1, gradeLevel: 1, theme: 'family' , sentence: 'My dad reads me a story every night.', sentenceCn: '我爸爸每晚给我读一个故事。' },
  { word: 'baby', translation: '宝宝', phonetic: '/ˈbeɪbi/', difficulty: 1, gradeLevel: 1, theme: 'family' , sentence: 'The baby is sleeping, please be quiet.', sentenceCn: '宝宝在睡觉，请安静。' },
  { word: 'love', translation: '爱', phonetic: '/lʌv/', difficulty: 1, gradeLevel: 1, theme: 'family' , sentence: 'I love my family more than anything.', sentenceCn: '我爱我的家人胜过一切。' },
  { word: 'home', translation: '家', phonetic: '/hoʊm/', difficulty: 1, gradeLevel: 1, theme: 'family' , sentence: 'There is no place like home.', sentenceCn: '没有比家更好的地方了。' },
  { word: 'mother', translation: '母亲', phonetic: '/ˈmʌðər/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'My mother gives me a hug every day.', sentenceCn: '我妈妈每天给我一个拥抱。' },
  { word: 'father', translation: '父亲', phonetic: '/ˈfɑːðər/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'My father teaches me how to ride a bike.', sentenceCn: '我爸爸教我骑自行车。' },
  { word: 'sister', translation: '姐妹', phonetic: '/ˈsɪstər/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'My sister helps me with my homework.', sentenceCn: '我姐姐帮我做作业。' },
  { word: 'brother', translation: '兄弟', phonetic: '/ˈbrʌðər/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'My little brother likes to play with me.', sentenceCn: '我弟弟喜欢和我一起玩。' },
  { word: 'family', translation: '家庭', phonetic: '/ˈfæməli/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'I love my family very much.', sentenceCn: '我非常爱我的家人。' },
  { word: 'grandma', translation: '奶奶/外婆', phonetic: '/ˈɡrænmɑː/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'Grandma tells me interesting stories.', sentenceCn: '奶奶给我讲有趣的故事。' },
  { word: 'grandpa', translation: '爷爷/外公', phonetic: '/ˈɡrænpɑː/', difficulty: 2, gradeLevel: 2, theme: 'family' , sentence: 'Grandpa takes me to the park on Sundays.', sentenceCn: '爷爷星期天带我去公园。' },
  { word: 'aunt', translation: '阿姨/姑姑', phonetic: '/ænt/', difficulty: 2, gradeLevel: 3, theme: 'family' , sentence: 'My aunt brought me a gift from her trip.', sentenceCn: '我阿姨旅行回来给我带了礼物。' },
  { word: 'uncle', translation: '叔叔/舅舅', phonetic: '/ˈʌŋkəl/', difficulty: 2, gradeLevel: 3, theme: 'family' , sentence: 'My uncle is very funny and makes us laugh.', sentenceCn: '我叔叔很幽默，总逗我们笑。' },
  { word: 'cousin', translation: '表亲', phonetic: '/ˈkʌzən/', difficulty: 3, gradeLevel: 3, theme: 'family' , sentence: 'My cousin and I are the same age.', sentenceCn: '我和表姐同龄。' },
  { word: 'parent', translation: '父母', phonetic: '/ˈperənt/', difficulty: 2, gradeLevel: 3, theme: 'family' , sentence: 'Parents work hard to take care of their children.', sentenceCn: '父母辛勤工作来照顾他们的孩子。' },
  { word: 'child', translation: '孩子', phonetic: '/tʃaɪld/', difficulty: 2, gradeLevel: 3, theme: 'family' , sentence: 'Every child has the right to go to school.', sentenceCn: '每个孩子都有上学的权利。' },
  { word: 'daughter', translation: '女儿', phonetic: '/ˈdɔːtər/', difficulty: 3, gradeLevel: 3, theme: 'family' , sentence: 'She is the youngest daughter in the family.', sentenceCn: '她是家里最小的女儿。' },
  { word: 'son', translation: '儿子', phonetic: '/sʌn/', difficulty: 1, gradeLevel: 3, theme: 'family' , sentence: 'Their son wants to be a doctor one day.', sentenceCn: '他们的儿子想有一天当医生。' },
  { word: 'husband', translation: '丈夫', phonetic: '/ˈhʌzbənd/', difficulty: 3, gradeLevel: 4, theme: 'family' , sentence: 'Her husband is a very kind and gentle man.', sentenceCn: '她的丈夫是一个非常和善温柔的男人。' },
  { word: 'wife', translation: '妻子', phonetic: '/waɪf/', difficulty: 2, gradeLevel: 4, theme: 'family' , sentence: 'His wife is a teacher at a primary school.', sentenceCn: '他的妻子是一所小学的老师。' },
  { word: 'nephew', translation: '侄子/外甥', phonetic: '/ˈnefjuː/', difficulty: 4, gradeLevel: 4, theme: 'family' , sentence: 'My nephew just started learning to walk.', sentenceCn: '我的小侄子刚开始学走路。' },
  { word: 'niece', translation: '侄女/外甥女', phonetic: '/niːs/', difficulty: 3, gradeLevel: 4, theme: 'family' , sentence: 'I bought a doll for my little niece.', sentenceCn: '我给小侄女买了一个娃娃。' },
  { word: 'relative', translation: '亲戚', phonetic: '/ˈrelətɪv/', difficulty: 4, gradeLevel: 4, theme: 'family' , sentence: 'Many relatives came to our family dinner.', sentenceCn: '很多亲戚来参加了我们的家庭聚餐。' },
  { word: 'twins', translation: '双胞胎', phonetic: '/twɪnz/', difficulty: 3, gradeLevel: 4, theme: 'family' , sentence: 'The twins look alike but have different ideas.', sentenceCn: '双胞胎长得很像但想法不同。' },
  { word: 'neighbor', translation: '邻居', phonetic: '/ˈneɪbər/', difficulty: 3, gradeLevel: 5, theme: 'family' , sentence: 'Our neighbor helped us fix the broken fence.', sentenceCn: '我们的邻居帮我们修好了坏掉的篱笆。' },
  { word: 'couple', translation: '夫妻', phonetic: '/ˈkʌpəl/', difficulty: 3, gradeLevel: 5, theme: 'family' , sentence: 'The old couple walks in the park every evening.', sentenceCn: '那对老夫妻每天傍晚在公园散步。' },
  { word: 'marriage', translation: '婚姻', phonetic: '/ˈmærɪdʒ/', difficulty: 4, gradeLevel: 5, theme: 'family' , sentence: 'They have a happy marriage of thirty years.', sentenceCn: '他们有着三十年幸福的婚姻。' },
  { word: 'generation', translation: '一代人', phonetic: '/ˌdʒenəˈreɪʃən/', difficulty: 5, gradeLevel: 5, theme: 'family' , sentence: 'Stories pass from one generation to the next.', sentenceCn: '故事从一代人传到下一代。' },
  { word: 'ancestor', translation: '祖先', phonetic: '/ˈænsestər/', difficulty: 5, gradeLevel: 6, theme: 'family' , sentence: 'We should always respect our ancestors.', sentenceCn: '我们应该永远尊重我们的祖先。' },
  { word: 'descendant', translation: '后代', phonetic: '/dɪˈsendənt/', difficulty: 5, gradeLevel: 6, theme: 'family' , sentence: 'We are the descendants of brave people.', sentenceCn: '我们是勇敢的人的后代。' },
  { word: 'heritage', translation: '遗产/传统', phonetic: '/ˈherɪtɪdʒ/', difficulty: 5, gradeLevel: 6, theme: 'family' , sentence: 'It is important to protect our cultural heritage.', sentenceCn: '保护我们的文化遗产很重要。' },
  { word: 'tradition', translation: '传统', phonetic: '/trəˈdɪʃən/', difficulty: 4, gradeLevel: 6, theme: 'family' , sentence: 'Eating dumplings is a New Year tradition.', sentenceCn: '吃饺子是新年的传统。' },
  { word: 'together', translation: '一起', phonetic: '/təˈɡeðər/', difficulty: 3, gradeLevel: 6, theme: 'family' , sentence: 'Let us sing this song together.', sentenceCn: '让我们一起唱这首歌。' },
  { word: 'share', translation: '分享', phonetic: '/ʃer/', difficulty: 2, gradeLevel: 6, theme: 'family' , sentence: 'It is good to share your toys with friends.', sentenceCn: '和朋友们分享玩具是好事。' },
  { word: 'care', translation: '关心', phonetic: '/ker/', difficulty: 2, gradeLevel: 6, theme: 'family' , sentence: 'Please take care of your little sister.', sentenceCn: '请照顾好你的小妹妹。' },
  { word: 'hug', translation: '拥抱', phonetic: '/hʌɡ/', difficulty: 2, gradeLevel: 6, theme: 'family' , sentence: 'A warm hug can make a bad day better.', sentenceCn: '一个温暖的拥抱能让糟糕的一天变好。' },
  { word: 'kind', translation: '善良的', phonetic: '/kaɪnd/', difficulty: 2, gradeLevel: 6, theme: 'family' , sentence: 'Being kind to others makes the world better.', sentenceCn: '善待他人让世界更美好。' },
  { word: 'polite', translation: '有礼貌的', phonetic: '/pəˈlaɪt/', difficulty: 3, gradeLevel: 6, theme: 'family' , sentence: 'Always be polite and say please and thank you.', sentenceCn: '要一直有礼貌，说请和谢谢。' },
  { word: 'respect', translation: '尊重', phonetic: '/rɪˈspekt/', difficulty: 4, gradeLevel: 6, theme: 'family' , sentence: 'We should respect our teachers and parents.', sentenceCn: '我们应该尊重老师和父母。' },
  { word: 'car', translation: '汽车', phonetic: '/kɑːr/', difficulty: 1, gradeLevel: 1, theme: 'transport' , sentence: 'My father drives a red car to work.', sentenceCn: '我爸爸开一辆红色的车去上班。' },
  { word: 'bus', translation: '公交车', phonetic: '/bʌs/', difficulty: 1, gradeLevel: 1, theme: 'transport' , sentence: 'I take the bus to school every day.', sentenceCn: '我每天坐公交车上学。' },
  { word: 'bike', translation: '自行车', phonetic: '/baɪk/', difficulty: 1, gradeLevel: 2, theme: 'transport' , sentence: 'Riding a bike is good exercise.', sentenceCn: '骑自行车是很好的锻炼。' },
  { word: 'taxi', translation: '出租车', phonetic: '/ˈtæksi/', difficulty: 2, gradeLevel: 2, theme: 'transport' , sentence: 'We took a taxi to the train station.', sentenceCn: '我们坐出租车去了火车站。' },
  { word: 'train', translation: '火车', phonetic: '/treɪn/', difficulty: 1, gradeLevel: 2, theme: 'transport' , sentence: 'The train goes faster than a car.', sentenceCn: '火车比汽车跑得快。' },
  { word: 'plane', translation: '飞机', phonetic: '/pleɪn/', difficulty: 1, gradeLevel: 2, theme: 'transport' , sentence: 'We will fly to Beijing by plane.', sentenceCn: '我们将乘飞机去北京。' },
  { word: 'boat', translation: '小船', phonetic: '/boʊt/', difficulty: 1, gradeLevel: 2, theme: 'transport' , sentence: 'We row a boat on the lake.', sentenceCn: '我们在湖上划船。' },
  { word: 'ship', translation: '轮船', phonetic: '/ʃɪp/', difficulty: 2, gradeLevel: 3, theme: 'transport' , sentence: 'A big ship sailed across the ocean.', sentenceCn: '一艘大轮船驶过了海洋。' },
  { word: 'subway', translation: '地铁', phonetic: '/ˈsʌbweɪ/', difficulty: 2, gradeLevel: 3, theme: 'transport' , sentence: 'The subway is the fastest way to go downtown.', sentenceCn: '地铁是去市中心最快的方式。' },
  { word: 'truck', translation: '卡车', phonetic: '/trʌk/', difficulty: 2, gradeLevel: 3, theme: 'transport' , sentence: 'A big truck delivers food to the store.', sentenceCn: '一辆大卡车把食物运到商店。' },
  { word: 'helicopter', translation: '直升机', phonetic: '/ˈhelɪkɑːptər/', difficulty: 4, gradeLevel: 3, theme: 'transport' , sentence: 'A helicopter can land in a very small space.', sentenceCn: '直升机能在很小的空间降落。' },
  { word: 'motorcycle', translation: '摩托车', phonetic: '/ˈmoʊtərsaɪkəl/', difficulty: 4, gradeLevel: 3, theme: 'transport' , sentence: 'He rides his motorcycle to work every day.', sentenceCn: '他每天骑摩托车上班。' },
  { word: 'traffic', translation: '交通', phonetic: '/ˈtræfɪk/', difficulty: 3, gradeLevel: 3, theme: 'transport' , sentence: 'There is heavy traffic on the road this morning.', sentenceCn: '今天早上路上交通很拥堵。' },
  { word: 'driver', translation: '司机', phonetic: '/ˈdraɪvər/', difficulty: 2, gradeLevel: 4, theme: 'transport' , sentence: 'A good driver always follows the rules.', sentenceCn: '好司机总是遵守规则。' },
  { word: 'passenger', translation: '乘客', phonetic: '/ˈpæsɪndʒər/', difficulty: 4, gradeLevel: 4, theme: 'transport' , sentence: 'Every passenger must wear a seat belt.', sentenceCn: '每位乘客都必须系好安全带。' },
  { word: 'station', translation: '车站', phonetic: '/ˈsteɪʃən/', difficulty: 3, gradeLevel: 4, theme: 'transport' , sentence: 'Meet me at the bus station at three o\'clock.', sentenceCn: '三点在公交车站见我。' },
  { word: 'airport', translation: '机场', phonetic: '/ˈerpɔːrt/', difficulty: 3, gradeLevel: 4, theme: 'transport' , sentence: 'We arrived at the airport two hours early.', sentenceCn: '我们提前两小时到达了机场。' },
  { word: 'bridge', translation: '桥', phonetic: '/brɪdʒ/', difficulty: 2, gradeLevel: 4, theme: 'transport' , sentence: 'We crossed a long bridge over the river.', sentenceCn: '我们过了河上一座很长的桥。' },
  { word: 'highway', translation: '高速公路', phonetic: '/ˈhaɪweɪ/', difficulty: 3, gradeLevel: 4, theme: 'transport' , sentence: 'The highway goes all the way to the city.', sentenceCn: '这条高速公路一直通到城市。' },
  { word: 'ambulance', translation: '救护车', phonetic: '/ˈæmbjələns/', difficulty: 4, gradeLevel: 5, theme: 'transport' , sentence: 'Call an ambulance if someone is badly hurt.', sentenceCn: '如果有人严重受伤就打急救电话。' },
  { word: 'vehicle', translation: '车辆', phonetic: '/ˈviːɪkəl/', difficulty: 4, gradeLevel: 5, theme: 'transport' , sentence: 'A bicycle is a simple but useful vehicle.', sentenceCn: '自行车是一种简单但很有用的车辆。' },
  { word: 'sail', translation: '航行', phonetic: '/seɪl/', difficulty: 3, gradeLevel: 5, theme: 'transport' , sentence: 'They plan to sail around the world one day.', sentenceCn: '他们计划有一天环游世界。' },
  { word: 'harbor', translation: '港口', phonetic: '/ˈhɑːrbər/', difficulty: 4, gradeLevel: 5, theme: 'transport' , sentence: 'Many fishing boats rest in the harbor at night.', sentenceCn: '很多渔船晚上停泊在港口。' },
  { word: 'railway', translation: '铁路', phonetic: '/ˈreɪlweɪ/', difficulty: 4, gradeLevel: 5, theme: 'transport' , sentence: 'The railway connects the two big cities.', sentenceCn: '这条铁路连接着两座大城市。' },
  { word: 'engine', translation: '引擎', phonetic: '/ˈendʒɪn/', difficulty: 3, gradeLevel: 5, theme: 'transport' , sentence: 'The car engine makes a loud sound.', sentenceCn: '汽车引擎发出很大的声音。' },
  { word: 'speed', translation: '速度', phonetic: '/spiːd/', difficulty: 2, gradeLevel: 5, theme: 'transport' , sentence: 'Do not drive over the speed limit.', sentenceCn: '不要超速驾驶。' },
  { word: 'direction', translation: '方向', phonetic: '/dɪˈrekʃən/', difficulty: 4, gradeLevel: 6, theme: 'transport' , sentence: 'Can you tell me the direction to the park?', sentenceCn: '你能告诉我公园的方向吗？' },
  { word: 'distance', translation: '距离', phonetic: '/ˈdɪstəns/', difficulty: 4, gradeLevel: 6, theme: 'transport' , sentence: 'The distance from home to school is two miles.', sentenceCn: '从家到学校的距离是两英里。' },
  { word: 'journey', translation: '旅程', phonetic: '/ˈdʒɜːrni/', difficulty: 3, gradeLevel: 6, theme: 'transport' , sentence: 'The journey to the mountains took three hours.', sentenceCn: '去山里的旅程花了三个小时。' },
  { word: 'destination', translation: '目的地', phonetic: '/ˌdestɪˈneɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'transport' , sentence: 'We reached our destination just before sunset.', sentenceCn: '我们在日落前到达了目的地。' },
  { word: 'transportation', translation: '运输', phonetic: '/ˌtrænspərˈteɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'transport' , sentence: 'Public transportation is good for the environment.', sentenceCn: '公共交通对环境有好处。' },
  { word: 'navigation', translation: '导航', phonetic: '/ˌnævɪˈɡeɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'transport' , sentence: 'We use a map for navigation on our trip.', sentenceCn: '我们在旅途中用地图来导航。' },
  { word: 'schedule', translation: '时刻表', phonetic: '/ˈskedʒuːl/', difficulty: 4, gradeLevel: 6, theme: 'transport' , sentence: 'Check the bus schedule before you leave home.', sentenceCn: '出门前查一下公交时刻表。' },
  { word: 'route', translation: '路线', phonetic: '/ruːt/', difficulty: 3, gradeLevel: 6, theme: 'transport' , sentence: 'This is the shortest route to the museum.', sentenceCn: '这是去博物馆最短的路线。' },
  { word: 'arrive', translation: '到达', phonetic: '/əˈraɪv/', difficulty: 2, gradeLevel: 6, theme: 'transport' , sentence: 'What time will we arrive at the hotel?', sentenceCn: '我们什么时候到达酒店？' },
  { word: 'tree', translation: '树', phonetic: '/triː/', difficulty: 1, gradeLevel: 1, theme: 'nature' , sentence: 'This big tree is over a hundred years old.', sentenceCn: '这棵大树有一百多岁了。' },
  { word: 'flower', translation: '花', phonetic: '/ˈflaʊər/', difficulty: 1, gradeLevel: 1, theme: 'nature' , sentence: 'I pick a flower for my mother.', sentenceCn: '我摘一朵花送给妈妈。' },
  { word: 'grass', translation: '草', phonetic: '/ɡræs/', difficulty: 1, gradeLevel: 1, theme: 'nature' , sentence: 'Do not walk on the grass, please.', sentenceCn: '请不要踩草地。' },
  { word: 'river', translation: '河流', phonetic: '/ˈrɪvər/', difficulty: 2, gradeLevel: 2, theme: 'nature' , sentence: 'The river flows gently through the town.', sentenceCn: '河水缓缓流过小镇。' },
  { word: 'mountain', translation: '山', phonetic: '/ˈmaʊntən/', difficulty: 2, gradeLevel: 2, theme: 'nature' , sentence: 'We climbed to the top of the mountain.', sentenceCn: '我们爬到了山顶。' },
  { word: 'sea', translation: '大海', phonetic: '/siː/', difficulty: 1, gradeLevel: 2, theme: 'nature' , sentence: 'I love to swim in the blue sea.', sentenceCn: '我喜欢在蓝色的大海里游泳。' },
  { word: 'forest', translation: '森林', phonetic: '/ˈfɔːrɪst/', difficulty: 3, gradeLevel: 2, theme: 'nature' , sentence: 'Many animals live in the deep forest.', sentenceCn: '很多动物住在茂密的森林里。' },
  { word: 'lake', translation: '湖', phonetic: '/leɪk/', difficulty: 2, gradeLevel: 2, theme: 'nature' , sentence: 'We went fishing at the lake last weekend.', sentenceCn: '上周末我们去湖边钓鱼了。' },
  { word: 'ocean', translation: '海洋', phonetic: '/ˈoʊʃən/', difficulty: 2, gradeLevel: 3, theme: 'nature' , sentence: 'The ocean covers most of our planet.', sentenceCn: '海洋覆盖了我们星球的大部分。' },
  { word: 'desert', translation: '沙漠', phonetic: '/ˈdezərt/', difficulty: 2, gradeLevel: 3, theme: 'nature' , sentence: 'Very few plants can grow in the desert.', sentenceCn: '很少植物能在沙漠里生长。' },
  { word: 'island', translation: '岛屿', phonetic: '/ˈaɪlənd/', difficulty: 2, gradeLevel: 3, theme: 'nature' , sentence: 'They found a small island in the middle of the sea.', sentenceCn: '他们在海中找到了一个小岛。' },
  { word: 'beach', translation: '海滩', phonetic: '/biːtʃ/', difficulty: 2, gradeLevel: 3, theme: 'nature' , sentence: 'We built a sand castle on the beach.', sentenceCn: '我们在海滩上建了一座沙堡。' },
  { word: 'waterfall', translation: '瀑布', phonetic: '/ˈwɔːtərfɔːl/', difficulty: 4, gradeLevel: 3, theme: 'nature' , sentence: 'The waterfall is so tall and loud.', sentenceCn: '瀑布又高又响。' },
  { word: 'volcano', translation: '火山', phonetic: '/vɑːlˈkeɪnoʊ/', difficulty: 4, gradeLevel: 4, theme: 'nature' , sentence: 'Smoke came out of the top of the volcano.', sentenceCn: '烟从火山顶冒了出来。' },
  { word: 'earthquake', translation: '地震', phonetic: '/ˈɜːrθkweɪk/', difficulty: 4, gradeLevel: 4, theme: 'nature' , sentence: 'The earthquake shook the ground for ten seconds.', sentenceCn: '地震摇晃了地面十秒钟。' },
  { word: 'valley', translation: '山谷', phonetic: '/ˈvæli/', difficulty: 3, gradeLevel: 4, theme: 'nature' , sentence: 'The valley between the hills is very green.', sentenceCn: '山丘之间的山谷非常翠绿。' },
  { word: 'cave', translation: '洞穴', phonetic: '/keɪv/', difficulty: 2, gradeLevel: 4, theme: 'nature' , sentence: 'Bats like to sleep inside the dark cave.', sentenceCn: '蝙蝠喜欢在黑暗的洞穴里睡觉。' },
  { word: 'jungle', translation: '丛林', phonetic: '/ˈdʒʌŋɡəl/', difficulty: 3, gradeLevel: 4, theme: 'nature' , sentence: 'The jungle is full of strange and wonderful plants.', sentenceCn: '丛林里长满了奇特美妙的植物。' },
  { word: 'coral', translation: '珊瑚', phonetic: '/ˈkɔːrəl/', difficulty: 3, gradeLevel: 4, theme: 'nature' , sentence: 'The coral reef is home to many sea creatures.', sentenceCn: '珊瑚礁是很多海洋生物的家。' },
  { word: 'fossil', translation: '化石', phonetic: '/ˈfɑːsəl/', difficulty: 3, gradeLevel: 4, theme: 'nature' , sentence: 'We found a dinosaur fossil in the rocks.', sentenceCn: '我们在岩石里发现了一块恐龙化石。' },
  { word: 'climate', translation: '气候', phonetic: '/ˈklaɪmət/', difficulty: 4, gradeLevel: 5, theme: 'nature' , sentence: 'The climate is changing around the world.', sentenceCn: '全球的气候正在变化。' },
  { word: 'ecosystem', translation: '生态系统', phonetic: '/ˈiːkoʊsɪstəm/', difficulty: 5, gradeLevel: 5, theme: 'nature' , sentence: 'Every ecosystem needs balance to stay healthy.', sentenceCn: '每个生态系统都需要平衡才能保持健康。' },
  { word: 'pollution', translation: '污染', phonetic: '/pəˈluːʃən/', difficulty: 4, gradeLevel: 5, theme: 'nature' , sentence: 'We must all work together to stop pollution.', sentenceCn: '我们必须一起努力来阻止污染。' },
  { word: 'recycle', translation: '回收', phonetic: '/riːˈsaɪkəl/', difficulty: 4, gradeLevel: 5, theme: 'nature' , sentence: 'Please recycle paper, glass, and plastic.', sentenceCn: '请回收纸张、玻璃和塑料。' },
  { word: 'energy', translation: '能源', phonetic: '/ˈenərdʒi/', difficulty: 3, gradeLevel: 5, theme: 'nature' , sentence: 'Solar energy comes from the sun.', sentenceCn: '太阳能来自太阳。' },
  { word: 'resource', translation: '资源', phonetic: '/ˈriːsɔːrs/', difficulty: 4, gradeLevel: 5, theme: 'nature' , sentence: 'Water is our most important natural resource.', sentenceCn: '水是我们最重要的自然资源。' },
  { word: 'wildlife', translation: '野生动植物', phonetic: '/ˈwaɪldlaɪf/', difficulty: 4, gradeLevel: 5, theme: 'nature' , sentence: 'We should protect wildlife and their homes.', sentenceCn: '我们应该保护野生动植物和它们的家园。' },
  { word: 'glacier', translation: '冰川', phonetic: '/ˈɡleɪʃər/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'Glaciers are slowly melting as the earth warms.', sentenceCn: '随着地球变暖，冰川正在慢慢融化。' },
  { word: 'avalanche', translation: '雪崩', phonetic: '/ˈævəlæntʃ/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'An avalanche of snow came down the mountain.', sentenceCn: '一场雪崩从山上滑落下来。' },
  { word: 'tsunami', translation: '海啸', phonetic: '/tsuːˈnɑːmi/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'A tsunami is a very large and dangerous wave.', sentenceCn: '海啸是非常大且危险的波浪。' },
  { word: 'horizon', translation: '地平线', phonetic: '/həˈraɪzən/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'We watched the sun go down below the horizon.', sentenceCn: '我们看着太阳落到地平线以下。' },
  { word: 'landscape', translation: '风景', phonetic: '/ˈlændskeɪp/', difficulty: 4, gradeLevel: 6, theme: 'nature' , sentence: 'The landscape from the hilltop was amazing.', sentenceCn: '从山顶看到的风景令人惊叹。' },
  { word: 'environment', translation: '环境', phonetic: '/ɪnˈvaɪrənmənt/', difficulty: 4, gradeLevel: 6, theme: 'nature' , sentence: 'We need to take care of our environment.', sentenceCn: '我们需要爱护我们的环境。' },
  { word: 'conservation', translation: '保护', phonetic: '/ˌkɑːnsərˈveɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'Forest conservation is important for our future.', sentenceCn: '森林保护对我们的未来很重要。' },
  { word: 'sustainable', translation: '可持续的', phonetic: '/səˈsteɪnəbəl/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'We should live in a more sustainable way.', sentenceCn: '我们应该以更可持续的方式生活。' },
  { word: 'biodiversity', translation: '生物多样性', phonetic: '/ˌbaɪoʊdaɪˈvɜːrsəti/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'Rainforests have the richest biodiversity on Earth.', sentenceCn: '雨林拥有地球上最丰富的生物多样性。' },
  { word: 'photosynthesis', translation: '光合作用', phonetic: '/ˌfoʊtoʊˈsɪnθəsɪs/', difficulty: 5, gradeLevel: 6, theme: 'nature' , sentence: 'Plants use photosynthesis to make their food.', sentenceCn: '植物通过光合作用来制造食物。' },
  { word: 'season', translation: '季节', phonetic: '/ˈsiːzən/', difficulty: 2, gradeLevel: 6, theme: 'nature' , sentence: 'My favorite season is spring with all the flowers.', sentenceCn: '我最喜欢的季节是百花盛开的春天。' },
  { word: 'spring', translation: '春天', phonetic: '/sprɪŋ/', difficulty: 2, gradeLevel: 6, theme: 'nature' , sentence: 'Spring is the time when flowers start to bloom.', sentenceCn: '春天是花朵开始绽放的时节。' },
  { word: 'autumn', translation: '秋天', phonetic: '/ˈɔːtəm/', difficulty: 2, gradeLevel: 6, theme: 'nature' , sentence: 'In autumn, the leaves turn yellow and red.', sentenceCn: '秋天，树叶变成黄色和红色。' },
  { word: 'book', translation: '书', phonetic: '/bʊk/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'I read a book every night before bed.', sentenceCn: '我每晚睡前读一本书。' },
  { word: 'pen', translation: '笔', phonetic: '/pen/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Please write your name with a pen.', sentenceCn: '请用笔写下你的名字。' },
  { word: 'desk', translation: '课桌', phonetic: '/desk/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Please keep your desk clean and tidy.', sentenceCn: '请保持你的课桌干净整洁。' },
  { word: 'bag', translation: '书包', phonetic: '/bæɡ/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'My school bag is very heavy today.', sentenceCn: '我的书包今天很重。' },
  { word: 'ruler', translation: '尺子', phonetic: '/ˈruːlər/', difficulty: 2, gradeLevel: 1, theme: 'school' , sentence: 'Use a ruler to draw a straight line.', sentenceCn: '用尺子画一条直线。' },
  { word: 'eraser', translation: '橡皮', phonetic: '/ɪˈreɪsər/', difficulty: 2, gradeLevel: 1, theme: 'school' , sentence: 'I use an eraser to fix my mistakes.', sentenceCn: '我用橡皮擦来改正错误。' },
  { word: 'teacher', translation: '老师', phonetic: '/ˈtiːtʃər/', difficulty: 2, gradeLevel: 2, theme: 'school' , sentence: 'Our teacher is very kind and patient.', sentenceCn: '我们的老师非常和蔼有耐心。' },
  { word: 'friend', translation: '朋友', phonetic: '/frend/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'A good friend is like a treasure.', sentenceCn: '好朋友就像宝藏一样。' },
  { word: 'pencil', translation: '铅笔', phonetic: '/ˈpensl/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'I need a pencil to draw a picture.', sentenceCn: '我需要一支铅笔来画画。' },
  { word: 'classroom', translation: '教室', phonetic: '/ˈklæsruːm/', difficulty: 3, gradeLevel: 2, theme: 'school' , sentence: 'The classroom is bright and clean.', sentenceCn: '教室明亮又干净。' },
  { word: 'homework', translation: '家庭作业', phonetic: '/ˈhoʊmwɜːrk/', difficulty: 2, gradeLevel: 2, theme: 'school' , sentence: 'I finish my homework before dinner.', sentenceCn: '我在晚饭前完成作业。' },
  { word: 'school', translation: '学校', phonetic: '/skuːl/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'I go to school by bus every morning.', sentenceCn: '我每天早上坐公交车上学。' },
  { word: 'playground', translation: '操场', phonetic: '/ˈpleɪɡraʊnd/', difficulty: 3, gradeLevel: 2, theme: 'school' , sentence: 'Children are playing on the playground.', sentenceCn: '孩子们在操场上玩耍。' },
  { word: 'read', translation: '阅读', phonetic: '/riːd/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'I can read ten pages of a book each night.', sentenceCn: '我每晚能读十页书。' },
  { word: 'write', translation: '写', phonetic: '/raɪt/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'Please write your name at the top of the page.', sentenceCn: '请在页面顶部写下你的名字。' },
  { word: 'library', translation: '图书馆', phonetic: '/ˈlaɪbreri/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'You can borrow books from the library.', sentenceCn: '你可以从图书馆借书。' },
  { word: 'science', translation: '科学', phonetic: '/ˈsaɪəns/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'Science helps us understand how the world works.', sentenceCn: '科学帮助我们理解世界是如何运作的。' },
  { word: 'notebook', translation: '笔记本', phonetic: '/ˈnoʊtbʊk/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'I wrote all my notes in a new notebook.', sentenceCn: '我把所有的笔记写在一个新笔记本里。' },
  { word: 'blackboard', translation: '黑板', phonetic: '/ˈblækbɔːrd/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'The teacher wrote the answer on the blackboard.', sentenceCn: '老师在黑板上写下了答案。' },
  { word: 'exercise', translation: '练习', phonetic: '/ˈeksərsaɪz/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'Do this math exercise before the next class.', sentenceCn: '下节课之前做完这道数学练习。' },
  { word: 'language', translation: '语言', phonetic: '/ˈlæŋɡwɪdʒ/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'Learning a new language opens many doors.', sentenceCn: '学一门新语言能打开很多扇门。' },
  { word: 'draw', translation: '画画', phonetic: '/drɔː/', difficulty: 1, gradeLevel: 3, theme: 'school' , sentence: 'I like to draw animals with colored pencils.', sentenceCn: '我喜欢用彩色铅笔画动物。' },
  { word: 'sing', translation: '唱歌', phonetic: '/sɪŋ/', difficulty: 1, gradeLevel: 3, theme: 'school' , sentence: 'The birds sing sweet songs in the morning.', sentenceCn: '鸟儿在清晨唱甜美的歌。' },
  { word: 'question', translation: '问题', phonetic: '/ˈkwestʃən/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'Raise your hand if you have a question.', sentenceCn: '如果有问题就举手。' },
  { word: 'answer', translation: '回答', phonetic: '/ˈænsər/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'Do you know the answer to this question?', sentenceCn: '你知道这个问题的答案吗？' },
  { word: 'subject', translation: '科目', phonetic: '/ˈsʌbdʒɪkt/', difficulty: 3, gradeLevel: 4, theme: 'school' , sentence: 'English is my favorite subject at school.', sentenceCn: '英语是我在学校最喜欢的科目。' },
  { word: 'dictionary', translation: '字典', phonetic: '/ˈdɪkʃəneri/', difficulty: 4, gradeLevel: 4, theme: 'school' , sentence: 'I use a dictionary to learn new words.', sentenceCn: '我用字典来学习新单词。' },
  { word: 'experiment', translation: '实验', phonetic: '/ɪkˈsperɪmənt/', difficulty: 4, gradeLevel: 4, theme: 'school' , sentence: 'We did a science experiment in class today.', sentenceCn: '今天我们课上做了一个科学实验。' },
  { word: 'history', translation: '历史', phonetic: '/ˈhɪstəri/', difficulty: 3, gradeLevel: 4, theme: 'school' , sentence: 'History teaches us about the past.', sentenceCn: '历史教我们了解过去。' },
  { word: 'geography', translation: '地理', phonetic: '/dʒiˈɑːɡrəfi/', difficulty: 4, gradeLevel: 4, theme: 'school' , sentence: 'In geography class, we learn about different countries.', sentenceCn: '在地理课上我们学习不同的国家。' },
  { word: 'math', translation: '数学', phonetic: '/mæθ/', difficulty: 2, gradeLevel: 4, theme: 'school' , sentence: 'I practice math problems every day after school.', sentenceCn: '我每天放学后练习数学题。' },
  { word: 'music', translation: '音乐', phonetic: '/ˈmjuːzɪk/', difficulty: 2, gradeLevel: 4, theme: 'school' , sentence: 'Music makes me feel happy and calm.', sentenceCn: '音乐让我感到快乐和平静。' },
  { word: 'art', translation: '美术', phonetic: '/ɑːrt/', difficulty: 2, gradeLevel: 4, theme: 'school' , sentence: 'Art class is my favorite part of the week.', sentenceCn: '美术课是我一周中最喜欢的部分。' },
  { word: 'grade', translation: '年级', phonetic: '/ɡreɪd/', difficulty: 2, gradeLevel: 4, theme: 'school' , sentence: 'She got a high grade on her science test.', sentenceCn: '她的科学考试得了高分。' },
  { word: 'exam', translation: '考试', phonetic: '/ɪɡˈzæm/', difficulty: 2, gradeLevel: 4, theme: 'school' , sentence: 'We have an English exam tomorrow.', sentenceCn: '我们明天有英语考试。' },
  { word: 'knowledge', translation: '知识', phonetic: '/ˈnɑːlɪdʒ/', difficulty: 3, gradeLevel: 5, theme: 'school' , sentence: 'Reading books gives us a lot of knowledge.', sentenceCn: '读书给我们很多知识。' },
  { word: 'education', translation: '教育', phonetic: '/ˌedʒuˈkeɪʃən/', difficulty: 4, gradeLevel: 5, theme: 'school' , sentence: 'Education is the key to a bright future.', sentenceCn: '教育是通向光明未来的钥匙。' },
  { word: 'university', translation: '大学', phonetic: '/ˌjuːnɪˈvɜːrsəti/', difficulty: 5, gradeLevel: 5, theme: 'school' , sentence: 'She wants to go to a good university one day.', sentenceCn: '她希望有一天能上一所好大学。' },
  { word: 'semester', translation: '学期', phonetic: '/sɪˈmestər/', difficulty: 4, gradeLevel: 5, theme: 'school' , sentence: 'We start a new semester in September.', sentenceCn: '我们九月份开始新学期。' },
  { word: 'graduation', translation: '毕业', phonetic: '/ˌɡrædʒuˈeɪʃən/', difficulty: 5, gradeLevel: 5, theme: 'school' , sentence: 'Graduation day is a very special and happy day.', sentenceCn: '毕业那天是非常特别和快乐的一天。' },
  { word: 'scholarship', translation: '奖学金', phonetic: '/ˈskɑːlərʃɪp/', difficulty: 5, gradeLevel: 5, theme: 'school' , sentence: 'She won a scholarship to study abroad.', sentenceCn: '她获得了去国外留学的奖学金。' },
  { word: 'research', translation: '研究', phonetic: '/rɪˈsɜːrtʃ/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'Scientists do research to find new cures.', sentenceCn: '科学家做研究来寻找新的疗法。' },
  { word: 'academic', translation: '学术的', phonetic: '/ˌækəˈdemɪk/', difficulty: 5, gradeLevel: 6, theme: 'school' , sentence: 'He worked hard to achieve academic success.', sentenceCn: '他努力学习取得了学术上的成功。' },
  { word: 'curriculum', translation: '课程', phonetic: '/kəˈrɪkjələm/', difficulty: 5, gradeLevel: 6, theme: 'school' , sentence: 'Our school has a very rich curriculum.', sentenceCn: '我们学校有非常丰富的课程。' },
  { word: 'essay', translation: '论文', phonetic: '/ˈeseɪ/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'I wrote a short essay about my summer holiday.', sentenceCn: '我写了一篇关于暑假的短文。' },
  { word: 'debate', translation: '辩论', phonetic: '/dɪˈbeɪt/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'We had a fun debate about the best pet.', sentenceCn: '我们就最好的宠物进行了一场有趣的辩论。' },
  { word: 'project', translation: '项目', phonetic: '/ˈprɑːdʒekt/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'Our group project is about protecting the ocean.', sentenceCn: '我们的小组项目是关于保护海洋的。' },
  { word: 'presentation', translation: '演讲', phonetic: '/ˌprezənˈteɪʃən/', difficulty: 5, gradeLevel: 6, theme: 'school' , sentence: 'I gave a presentation about pandas in class.', sentenceCn: '我在班上做了一个关于熊猫的演讲。' },
  { word: 'creative', translation: '有创意的', phonetic: '/kriˈeɪtɪv/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'Drawing and painting help you be more creative.', sentenceCn: '绘画和画画能让你更有创意。' },
  { word: 'curious', translation: '好奇的', phonetic: '/ˈkjʊriəs/', difficulty: 4, gradeLevel: 6, theme: 'school' , sentence: 'A curious child always asks many questions.', sentenceCn: '好奇的孩子总是问很多问题。' },
  { word: 'sun', translation: '太阳', phonetic: '/sʌn/', difficulty: 1, gradeLevel: 1, theme: 'space' , sentence: 'The sun gives us light and warmth.', sentenceCn: '太阳给我们光和温暖。' },
  { word: 'moon', translation: '月亮', phonetic: '/muːn/', difficulty: 1, gradeLevel: 1, theme: 'space' , sentence: 'The moon is round and bright tonight.', sentenceCn: '今晚的月亮又圆又亮。' },
  { word: 'star', translation: '星星', phonetic: '/stɑːr/', difficulty: 1, gradeLevel: 1, theme: 'space' , sentence: 'I can see many stars in the night sky.', sentenceCn: '我在夜空中能看到很多星星。' },
  { word: 'sky', translation: '天空', phonetic: '/skaɪ/', difficulty: 1, gradeLevel: 1, theme: 'space' , sentence: 'The sky is full of stars at night.', sentenceCn: '夜晚的天空布满星星。' },
  { word: 'earth', translation: '地球', phonetic: '/ɜːrθ/', difficulty: 2, gradeLevel: 2, theme: 'space' , sentence: 'We all live on the planet Earth.', sentenceCn: '我们都生活在地球上。' },
  { word: 'planet', translation: '行星', phonetic: '/ˈplænɪt/', difficulty: 3, gradeLevel: 3, theme: 'space' , sentence: 'Mars is a red planet close to Earth.', sentenceCn: '火星是靠近地球的红色行星。' },
  { word: 'rocket', translation: '火箭', phonetic: '/ˈrɑːkɪt/', difficulty: 2, gradeLevel: 3, theme: 'space' , sentence: 'The rocket flies into space.', sentenceCn: '火箭飞向太空。' },
  { word: 'astronaut', translation: '宇航员', phonetic: '/ˈæstrənɔːt/', difficulty: 4, gradeLevel: 3, theme: 'space' , sentence: 'I want to be an astronaut when I grow up.', sentenceCn: '我长大后想当宇航员。' },
  { word: 'galaxy', translation: '银河', phonetic: '/ˈɡæləksi/', difficulty: 4, gradeLevel: 4, theme: 'space' , sentence: 'Our solar system is part of a huge galaxy.', sentenceCn: '我们的太阳系是一个巨大银河系的一部分。' },
  { word: 'comet', translation: '彗星', phonetic: '/ˈkɑːmɪt/', difficulty: 3, gradeLevel: 4, theme: 'space' , sentence: 'A comet has a bright tail of ice and dust.', sentenceCn: '彗星有一条由冰和尘埃组成的亮尾巴。' },
  { word: 'orbit', translation: '轨道', phonetic: '/ˈɔːrbɪt/', difficulty: 3, gradeLevel: 4, theme: 'space' , sentence: 'The moon moves in orbit around the Earth.', sentenceCn: '月亮沿轨道绕地球运行。' },
  { word: 'satellite', translation: '卫星', phonetic: '/ˈsætəlaɪt/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'Satellites help us get weather information.', sentenceCn: '卫星帮我们获取天气信息。' },
  { word: 'telescope', translation: '望远镜', phonetic: '/ˈtelɪskoʊp/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'I looked at the moon through my telescope.', sentenceCn: '我通过望远镜看月亮。' },
  { word: 'universe', translation: '宇宙', phonetic: '/ˈjuːnɪvɜːrs/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'The universe is so big we cannot measure it.', sentenceCn: '宇宙太大了，我们无法测量它。' },
  { word: 'gravity', translation: '重力', phonetic: '/ˈɡrævəti/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'Gravity is what keeps us on the ground.', sentenceCn: '重力是让我们站在地面上的力量。' },
  { word: 'atmosphere', translation: '大气层', phonetic: '/ˈætməsfɪr/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'The atmosphere protects Earth from the sun.', sentenceCn: '大气层保护地球免受太阳伤害。' },
  { word: 'constellation', translation: '星座', phonetic: '/ˌkɑːnstəˈleɪʃn/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'We learned about the Big Bear constellation.', sentenceCn: '我们学习了大熊星座。' },
  { word: 'meteor', translation: '流星', phonetic: '/ˈmiːtiər/', difficulty: 3, gradeLevel: 5, theme: 'space' , sentence: 'We saw a bright meteor shoot across the sky.', sentenceCn: '我们看到一颗明亮的流星划过天空。' },
  { word: 'eclipse', translation: '日食/月食', phonetic: '/ɪˈklɪps/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'A solar eclipse is a rare and beautiful sight.', sentenceCn: '日食是罕见而美丽的景象。' },
  { word: 'nebula', translation: '星云', phonetic: '/ˈnebjələ/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'A nebula is a giant cloud of gas in space.', sentenceCn: '星云是太空中巨大的气体云。' },
  { word: 'spacecraft', translation: '宇宙飞船', phonetic: '/ˈspeɪskræft/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'The spacecraft landed safely on the moon.', sentenceCn: '宇宙飞船安全地降落在月球上。' },
  { word: 'alien', translation: '外星人', phonetic: '/ˈeɪliən/', difficulty: 3, gradeLevel: 3, theme: 'space' , sentence: 'Do you think aliens live on other planets?', sentenceCn: '你觉得其他行星上有外星人吗？' },
  { word: 'asteroid', translation: '小行星', phonetic: '/ˈæstərɔɪd/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'An asteroid hit the Earth millions of years ago.', sentenceCn: '几百万年前一颗小行星撞击了地球。' },
  { word: 'black hole', translation: '黑洞', phonetic: '/blæk hoʊl/', difficulty: 4, gradeLevel: 6, theme: 'space' , sentence: 'A black hole pulls in everything, even light.', sentenceCn: '黑洞会吸入一切，连光也不例外。' },
  { word: 'spaceship', translation: '太空船', phonetic: '/ˈspeɪsʃɪp/', difficulty: 3, gradeLevel: 4, theme: 'space' , sentence: 'The spaceship is ready for its next big trip.', sentenceCn: '太空船为下一次大旅程做好了准备。' },
  { word: 'launch', translation: '发射', phonetic: '/lɔːntʃ/', difficulty: 3, gradeLevel: 4, theme: 'space' , sentence: 'They will launch the rocket tomorrow morning.', sentenceCn: '他们明天早上将发射火箭。' },
  { word: 'explore', translation: '探索', phonetic: '/ɪkˈsplɔːr/', difficulty: 3, gradeLevel: 5, theme: 'space' , sentence: 'We hope to explore Mars in the future.', sentenceCn: '我们希望未来能探索火星。' },
  { word: 'mission', translation: '任务', phonetic: '/ˈmɪʃən/', difficulty: 4, gradeLevel: 6, theme: 'space' , sentence: 'The space mission lasted for six months.', sentenceCn: '这次太空任务持续了六个月。' },
  { word: 'discovery', translation: '发现', phonetic: '/dɪˈskʌvəri/', difficulty: 4, gradeLevel: 6, theme: 'space' , sentence: 'Every new discovery helps us learn more.', sentenceCn: '每一个新发现都帮助我们了解更多。' },
  { word: 'solar', translation: '太阳的', phonetic: '/ˈsoʊlər/', difficulty: 4, gradeLevel: 6, theme: 'space' , sentence: 'Solar panels turn sunlight into electricity.', sentenceCn: '太阳能板把阳光变成电。' },
  { word: 'cosmic', translation: '宇宙的', phonetic: '/ˈkɑːzmɪk/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'Cosmic rays come from far away in space.', sentenceCn: '宇宙射线来自太空的远方。' },
  { word: 'lightyear', translation: '光年', phonetic: '/ˈlaɪtjɪr/', difficulty: 5, gradeLevel: 6, theme: 'space' , sentence: 'A lightyear is the distance light travels in one year.', sentenceCn: '光年是光在一年里走的距离。' },
  { word: 'Martian', translation: '火星人', phonetic: '/ˈmɑːrʃən/', difficulty: 4, gradeLevel: 5, theme: 'space' , sentence: 'In the movie, a Martian visits Earth.', sentenceCn: '在电影里，一个火星人来到了地球。' },
  { word: 'UFO', translation: '不明飞行物', phonetic: '/juː ef oʊ/', difficulty: 3, gradeLevel: 4, theme: 'space' , sentence: 'People say they saw a UFO in the night sky.', sentenceCn: '人们说他们在夜空中看到了不明飞行物。' },
  { word: 'wonder', translation: '奇迹/好奇', phonetic: '/ˈwʌndər/', difficulty: 3, gradeLevel: 5, theme: 'space' , sentence: 'I look at the stars and wonder what is out there.', sentenceCn: '我望着星星，想知道外面有什么。' },
  { word: 'hello', translation: '你好', phonetic: '/həˈloʊ/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Say hello to the new student in our class.', sentenceCn: '跟我们班的新同学打个招呼吧。' },
  { word: 'goodbye', translation: '再见', phonetic: '/ɡʊdˈbaɪ/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Wave goodbye to your friends after school.', sentenceCn: '放学后跟朋友们挥手再见。' },
  { word: 'please', translation: '请', phonetic: '/pliːz/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Please open your book to page ten.', sentenceCn: '请把书翻到第十页。' },
  { word: 'thank', translation: '谢谢', phonetic: '/θæŋk/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Do not forget to say thank you to your teacher.', sentenceCn: '别忘了对老师说谢谢。' },
  { word: 'sorry', translation: '对不起', phonetic: '/ˈsɑːri/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'I am sorry I broke your pencil by accident.', sentenceCn: '对不起，我不小心弄断了你的铅笔。' },
  { word: 'yes', translation: '是的', phonetic: '/jes/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Yes, I would like to join the school club.', sentenceCn: '是的，我想加入学校社团。' },
  { word: 'no', translation: '不', phonetic: '/noʊ/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'No, I have not finished my drawing yet.', sentenceCn: '不，我还没有画完我的画。' },
  { word: 'happy', translation: '快乐的', phonetic: '/ˈhæpi/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'I feel so happy when I play with my friends.', sentenceCn: '和朋友们一起玩的时候我很快乐。' },
  { word: 'sad', translation: '悲伤的', phonetic: '/sæd/', difficulty: 1, gradeLevel: 1, theme: 'color' , sentence: 'She felt sad when her pet fish died.', sentenceCn: '她的宠物鱼死了，她很伤心。' },
  { word: 'big', translation: '大的', phonetic: '/bɪɡ/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'The elephant is a very big animal.', sentenceCn: '大象是非常大的动物。' },
  { word: 'small', translation: '小的', phonetic: '/smɔːl/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'A small bird sat on the window.', sentenceCn: '一只小鸟停在窗户上。' },
  { word: 'tall', translation: '高的', phonetic: '/tɔːl/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'My big brother is very tall.', sentenceCn: '我的大哥哥个子很高。' },
  { word: 'short', translation: '矮的/短的', phonetic: '/ʃɔːrt/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'The rabbit has short ears and a round body.', sentenceCn: '兔子有短耳朵和圆圆的身体。' },
  { word: 'long', translation: '长的', phonetic: '/lɒŋ/', difficulty: 1, gradeLevel: 1, theme: 'body' , sentence: 'The snake has a very long body.', sentenceCn: '蛇有非常长的身体。' },
  { word: 'new', translation: '新的', phonetic: '/nuː/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'I got a new backpack for the school year.', sentenceCn: '我为新学年买了一个新书包。' },
  { word: 'old', translation: '旧的/老的', phonetic: '/oʊld/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'This old book belongs to my grandfather.', sentenceCn: '这本旧书是我爷爷的。' },
  { word: 'good', translation: '好的', phonetic: '/ɡʊd/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'It is a good habit to read before you sleep.', sentenceCn: '睡前阅读是个好习惯。' },
  { word: 'bad', translation: '坏的', phonetic: '/bæd/', difficulty: 1, gradeLevel: 1, theme: 'school' , sentence: 'Eating too much candy is a bad habit.', sentenceCn: '吃太多糖是个坏习惯。' },
  { word: 'pretty', translation: '漂亮的', phonetic: '/ˈprɪti/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'You look very pretty in that new dress.', sentenceCn: '你穿那条新裙子很漂亮。' },
  { word: 'ugly', translation: '丑陋的', phonetic: '/ˈʌɡli/', difficulty: 2, gradeLevel: 2, theme: 'color' , sentence: 'Do not call anyone ugly, it is not kind.', sentenceCn: '不要说别人丑，这样不善良。' },
  { word: 'fast', translation: '快的', phonetic: '/fæst/', difficulty: 1, gradeLevel: 2, theme: 'sports' , sentence: 'The cheetah is the fastest animal on land.', sentenceCn: '猎豹是陆地上最快的动物。' },
  { word: 'slow', translation: '慢的', phonetic: '/sloʊ/', difficulty: 1, gradeLevel: 2, theme: 'sports' , sentence: 'The turtle is slow but never gives up.', sentenceCn: '乌龟很慢但从不放弃。' },
  { word: 'heavy', translation: '重的', phonetic: '/ˈhevi/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'This box is too heavy for me to carry.', sentenceCn: '这个箱子太重了，我搬不动。' },
  { word: 'light', translation: '轻的', phonetic: '/laɪt/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'A feather is very light and soft.', sentenceCn: '羽毛又轻又软。' },
  { word: 'soft', translation: '柔软的', phonetic: '/sɒft/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'The kitten has soft, warm fur.', sentenceCn: '小猫有柔软温暖的毛。' },
  { word: 'hard', translation: '硬的/困难的', phonetic: '/hɑːrd/', difficulty: 2, gradeLevel: 2, theme: 'body' , sentence: 'This rock is hard and smooth.', sentenceCn: '这块石头又硬又光滑。' },
  { word: 'clean', translation: '干净的', phonetic: '/kliːn/', difficulty: 2, gradeLevel: 2, theme: 'nature' , sentence: 'Keep the park clean, do not litter.', sentenceCn: '保持公园干净，不要乱扔垃圾。' },
  { word: 'dirty', translation: '脏的', phonetic: '/ˈdɜːrti/', difficulty: 2, gradeLevel: 2, theme: 'nature' , sentence: 'Wash your dirty hands before you eat.', sentenceCn: '吃东西前把脏手洗干净。' },
  { word: 'open', translation: '打开', phonetic: '/ˈoʊpən/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'Open the window and let some fresh air in.', sentenceCn: '打开窗户让新鲜空气进来。' },
  { word: 'close', translation: '关闭', phonetic: '/kloʊz/', difficulty: 1, gradeLevel: 2, theme: 'school' , sentence: 'Close the door quietly when you leave.', sentenceCn: '离开时轻轻关上门。' },
  { word: 'begin', translation: '开始', phonetic: '/bɪˈɡɪn/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'Let us begin our lesson with a fun song.', sentenceCn: '让我们用一首有趣的歌开始上课。' },
  { word: 'finish', translation: '完成', phonetic: '/ˈfɪnɪʃ/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'Please finish your homework before you play.', sentenceCn: '玩之前请先完成你的作业。' },
  { word: 'remember', translation: '记住', phonetic: '/rɪˈmembər/', difficulty: 3, gradeLevel: 3, theme: 'school' , sentence: 'Remember to bring your library book tomorrow.', sentenceCn: '记得明天带你的图书馆借书来。' },
  { word: 'forget', translation: '忘记', phonetic: '/fərˈɡet/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'Do not forget to feed the cat before school.', sentenceCn: '上学前别忘了喂猫。' },
  { word: 'believe', translation: '相信', phonetic: '/bɪˈliːv/', difficulty: 3, gradeLevel: 4, theme: 'school' , sentence: 'I believe you can do anything if you try hard.', sentenceCn: '我相信只要你努力就能做到任何事。' },
  { word: 'imagine', translation: '想象', phonetic: '/ɪˈmædʒɪn/', difficulty: 3, gradeLevel: 4, theme: 'school' , sentence: 'Close your eyes and imagine a beautiful garden.', sentenceCn: '闭上眼睛想象一个美丽的花园。' },
  { word: 'dream', translation: '梦想', phonetic: '/driːm/', difficulty: 2, gradeLevel: 3, theme: 'space' , sentence: 'My dream is to become a space scientist.', sentenceCn: '我的梦想是成为一名太空科学家。' },
  { word: 'wish', translation: '愿望', phonetic: '/wɪʃ/', difficulty: 2, gradeLevel: 3, theme: 'space' , sentence: 'I wish upon a star for a happy new year.', sentenceCn: '我对着星星许愿新年快乐。' },
  { word: 'magic', translation: '魔法', phonetic: '/ˈmædʒɪk/', difficulty: 3, gradeLevel: 3, theme: 'space' , sentence: 'The night sky feels full of magic and wonder.', sentenceCn: '夜空充满了魔力和奇迹。' },
  { word: 'brave', translation: '勇敢的', phonetic: '/breɪv/', difficulty: 2, gradeLevel: 3, theme: 'sports' , sentence: 'Be brave and try new things every day.', sentenceCn: '要勇敢，每天尝试新事物。' },
  { word: 'clever', translation: '聪明的', phonetic: '/ˈklevər/', difficulty: 2, gradeLevel: 3, theme: 'school' , sentence: 'She is clever and learns new things quickly.', sentenceCn: '她很聪明，学新东西很快。' },
  { word: 'honest', translation: '诚实的', phonetic: '/ˈɑːnɪst/', difficulty: 3, gradeLevel: 4, theme: 'family' , sentence: 'An honest person always tells the truth.', sentenceCn: '诚实的人总是说真话。' },
  { word: 'patient', translation: '耐心的', phonetic: '/ˈpeɪʃənt/', difficulty: 3, gradeLevel: 4, theme: 'family' , sentence: 'A good teacher is patient with every student.', sentenceCn: '好老师对每个学生都有耐心。' },
  { word: 'special', translation: '特别的', phonetic: '/ˈspeʃəl/', difficulty: 3, gradeLevel: 4, theme: 'color' , sentence: 'Today is a special day because it is my birthday.', sentenceCn: '今天是特别的一天，因为是我的生日。' },
  { word: 'wonderful', translation: '精彩的', phonetic: '/ˈwʌndərfəl/', difficulty: 3, gradeLevel: 4, theme: 'color' , sentence: 'We had a wonderful time at the beach.', sentenceCn: '我们在海滩度过了精彩的时光。' },
]